import type { Section } from "../hotels";

/** Final, property-specific reporting added after the catalogue-wide depth audit. */
export const individualReviewFinishes: Record<string, Section[]> = {
  "post-ranch-inn-big-sur": [{ heading: "The room is a choice between ocean and forest", body: [
    "Post Ranch has no anonymous middle category. Cliff House and Pacific Suite curve toward the ocean; Ocean House disappears beneath a planted roof; Peak House looks inland across the Santa Lucia Mountains; Tree House stands on stilts among the redwoods. None has a television or alarm clock, an omission that feels principled until a guest needs a score or an early departure. Every room is designed for two and has one king bed, so this is emphatically a couples' retreat rather than a flexible family resort.",
    "The rate makes more sense once its inclusions are counted: breakfast at Sierra Mar, the minibar, guided nature walks, yoga and access to pools are part of the stay, though spa treatments and gratuities are not. Sierra Mar now holds a Michelin Green Star and draws much of its produce from the ranch garden and nearby farms. Dinner is required booking; breakfast is reserved for residents. The wine cellar is deep enough to become the evening's central pleasure, but the window remains the restaurant's most powerful course.",
    "A newly expanded, guests-only spa has five treatment spaces framed by redwoods, including the private Redwood Sanctuary for couples. Book it with the room, not after arrival. Highway 1 closures and coastal weather can rewrite access with little notice, and mobile reception is unreliable by design as much as geography. Arrive before dark, bring layers and resist scheduling Big Sur as a one-night scenic stop. Two nights reveal the architecture; three allow the silence to do its work."
  ]}],
  "the-connaught-london": [{ heading: "The useful distinction is old wing or contemporary wing", body: [
    "The Connaught's rooms are not variations on one template. Guy Oliver's classical spaces use antiques, restrained colour and the proportions of the original building; India Mahdavi's contemporary wing is lighter, more graphic and often the better answer for a guest who admires the hotel but not Edwardian cosiness. Recently restored suites extend the choice again, some with terraces and all with butler service. Ask to see the precise room plan and design language before confirming: at this level, an aesthetic mismatch is an expensive error.",
    "Downstairs, the hotel is unusually complete without becoming sprawling. Hélène Darroze's restaurant holds three Michelin stars; Jean-Georges handles a more relaxed all-day appetite; the rosewood-lined Connaught Grill restores the pleasure of a proper grill room. The Connaught Bar's martini trolley deserves its fame, though residents should not assume a spontaneous prime-time seat. Beneath it all, the Aman Spa—Aman's first outside one of its resorts—contains a pool, steam room and treatment spaces that feel almost implausibly removed from Carlos Place.",
    "The weakness is the same as the strength: the house is discreet, compact and intensely popular. Public rooms can feel claimed by regulars, entry rooms are not enormous and Mayfair prices follow the postcode. What the premium buys is fluency. Doors open before the request forms, names travel between shifts and a complicated London day is quietly edited into something manageable."
  ]}],
  "splendido-portofino": [{ heading: "A new chapter behind the familiar façade", body: [
    "Splendido has emerged from a major Belmond restoration with fewer keys than older guidebooks report: the current hotel lists 53 rooms and suites. Martin Brudnizki's work keeps the Ligurian palette—sun-faded pink, green shutters, botanical pattern—while loosening some of the former grand-hotel stiffness. The Dior Spa is another important change. This is still a summer residence above a fishing harbour, but no longer one relying on nostalgia alone to justify the rate.",
    "The room decision begins with altitude and outlook. Signature suites run from 55 to 127 square metres, yet a smaller terrace directly over the bay can be more emotionally useful than interior acreage. Confirm whether a promised sea view includes the harbour, open water or foliage, and remember that the building's historic plan creates steps and long routes. The hotel lists two restaurants and a cocktail bar; reserve the principal terrace for one evening, then use the complimentary shuttle to eat by the piazzetta at sister property Splendido Mare.",
    "Portofino's beauty is real and its summer pressure equally so. Day boats, narrow roads and a tiny harbour can make simple outings slow. The hotel is best treated as the destination, with one boat day and one walk into the regional park, rather than headquarters for a frantic Ligurian itinerary. Come in June or September when the pool is persuasive but the village still has room to breathe."
  ]}],
  "mandarin-oriental-bangkok": [{ heading: "The river is the organising principle", body: [
    "The Mandarin Oriental does not merely overlook the Chao Phraya; it uses the river as corridor, clock and theatre. Boats carry guests to the Oriental Spa in its restored teak house and to the Thai dining rooms across the water. Ferries, long-tail boats and barges animate breakfast without turning the hotel into a spectacle. A river-facing room is therefore the essential purchase. The renewed River Wing has floor-to-ceiling glass and contemporary Thai references, while the Authors' Wing preserves the more literary, colonial-era atmosphere associated with the house.",
    "Dining has become a small district of its own. Anne-Sophie Pic at Le Normandie holds two Michelin stars; Baan Phraya and Sala Rim Naam explore Thai cooking in different registers; the Authors' Lounge serves afternoon tea; the Bamboo Bar remains the address for live jazz and serious drinks. There are 12 restaurants and bars in the present line-up, too many to complete and a useful reason to choose selectively. Book the ambitious dinner, then spend another night eating in Bangkok rather than confusing breadth with obligation.",
    "The Oriental Spa now has 18 treatment rooms and draws from Thai and Chinese traditions, with the boat crossing providing a rare ceremonial beginning. Traffic makes river transport valuable, but the hotel is not beside a BTS station; Silom Road and Saphan Taksin require a walk, boat or car. The service legacy is formidable, yet the most modern rooms and the oldest public spaces deliberately speak different dialects. Guests wanting seamless newness may prefer a tower; those who value accumulated character will understand why this address has endured for more than 150 years."
  ]}],
  "copacabana-palace-rio": [{ heading: "Read the renovation calendar before the room list", body: [
    "Copacabana Palace is in the middle of a consequential renewal. Belmond says the annex and main pool are undergoing work through parts of 2026, with the Pool Wing returning as a showcase for Brazilian designers and artisans; during the principal pool closure, residents are directed to a sixth-floor alternative. The main building continues to operate, but this is not a footnote when the half-Olympic pool is one of the hotel's signatures. Confirm the exact dates, construction outlook and available facilities in writing before paying a peak-season rate.",
    "The current inventory is 140 rooms and suites, ranging from 26-square-metre rooms to vast signature accommodation. Ocean-facing rooms in the historic building deliver the striped promenade and Atlantic; inner views trade drama for calm. Pérgula serves Brazilian and Mediterranean food, MEE holds a Michelin star for pan-Asian cooking, and the hotel advertises two Michelin-starred restaurants overall. The spa and salon have also had temporary renovation closures, another reason to treat old reviews cautiously.",
    "Security, beach access and transport are handled with the confidence expected of the address, but Rio is not best experienced through the hotel window. Use the private beach set-up, walk the promenade in daylight and allow generous time for trips to Ipanema, Santa Teresa and the mountains. The Copa is a grand social stage beside a democratic city beach; its magic lies in that friction, not in pretending the city has been kept outside."
  ]}],
  "royal-mansour-marrakech": [{ heading: "Privacy is engineered beneath the medina", body: [
    "There are no conventional rooms. Fifty-three riads, each arranged over three floors, line a purpose-built medina of lanes, courtyards and carved doors. Even the smallest has a salon, bedroom and roof terrace; larger houses add bedrooms, dining rooms and pools. An underground service network allows staff to move almost invisibly beneath the property. It is a brilliant piece of hospitality engineering and occasionally uncanny: guests who enjoy the sociability of a hotel corridor may find the privacy too complete.",
    "The riad category should follow mobility as well as budget. Repeated stairs connect living room, bedroom and roof, and the most romantic terrace is less useful if every forgotten book requires another climb. Ask about lift access, pool heating, sun and proximity to the main facilities. The 2,500-square-metre spa occupies three floors around its famous white lattice atrium, while Le Jardin provides the outdoor pool and a greener, more social daytime rhythm.",
    "Four signature restaurants currently divide the appetite among Moroccan, Italian, French and Asian ideas. The craft throughout—zellige, carved plaster, cedar, metalwork—is not surface decoration but the hotel's central argument for Moroccan excellence. Yet the gates sit close to the old city. A private riad should make entry into the medina more confident, not unnecessary; the comparison between living craft outside and its palace-level expression within is what gives the stay intellectual as well as sensual weight."
  ]}],
  "bulgari-resort-dubai": [{ heading: "The practical test of all that restraint", body: [
    "Dubai's heat determines how the resort works. From late autumn to spring, breakfast terraces, marina walks and the beach connect the limestone buildings into a coherent Mediterranean village. In midsummer those distances become air-conditioned transfers, and the small private beach can feel secondary to pool and spa. Sea conditions are gentle rather than dramatic; anyone expecting a natural Gulf wilderness should understand that Jumeira Bay is a designed island.",
    "Families should compare a two-bedroom villa with connecting rooms rather than assume the villa is automatically superior. Villas bring a private pool and butler attention, but their seclusion can isolate children from the main pool and club. Couples may find a high sea-view room more elegant and socially connected. At every level, request the total price including taxes, meals and transfers: Bulgari's calm visual language does not translate into modest incidental costs."
  ]}],
  "raffles-singapore": [{ heading: "The question is how much history to consume", body: [
    "Every accommodation is a suite, but position changes the experience. Courtyard Suites face the arcades and garden; Palm Court Suites look toward the quieter central lawn; personality suites attach the room to a former guest. Ground-floor verandas are atmospheric and less private when visitors are circulating. Upper-floor rooms involve more stairs and distance but generally feel removed from the public gaze. The building rewards a precise conversation with reservations rather than a blind category upgrade.",
    "Non-residents arrive for photographs, shopping and the Singapore Sling, and the Long Bar can feel more pilgrimage than cocktail hour. Residents have access to quieter spaces and should use them: an early lap in the rooftop pool, breakfast before the arcades fill, a late walk through the Palm Court. The restoration has made modern systems largely invisible. That is the correct achievement here—not turning an 1887 monument into a new hotel, but allowing it to function like one."
  ]}],
  "stay-wellbeing-phuket": [{ heading: "Wellness here is active, not ornamental", body: [
    "STAY is built around a serious fitness proposition. Its three-storey gym, group studios, Muay Thai, functional training and recovery facilities attract residents who intend to train rather than merely admire a yoga mat in the wardrobe. That gives the resort a purposeful morning energy and can surprise travellers expecting the languor of a conventional Phuket escape. Programme times, coaching and class inclusions vary by package; confirm them before building a week around the timetable.",
    "The Rawai location is useful for southern beaches, Chalong pier and longer stays, but it is not a walk-out beachfront setting. A car or arranged transport is part of the practical budget. Apartments with kitchens suit nutrition-conscious guests and families; pool-access rooms trade privacy for convenience. The best stay alternates exercise with actual island life—Nai Harn early, seafood by the water, then recovery back at the resort—rather than turning Phuket into a backdrop for a gym membership."
  ]}],
  "four-seasons-george-v-paris": [{ heading: "Service is the hidden fourth restaurant", body: [
    "Six Michelin stars across three restaurants create obvious theatre, but the more revealing performance happens between meals. A palace of 243 rooms has luggage, florists, security, chauffeurs, families and non-resident diners moving through it at once. The concierge and floor teams make that density feel personal by remembering timing and preferences rather than relying on grand gestures. Ask them to edit the itinerary; Paris becomes exhausting when every celebrated reservation is treated as compulsory.",
    "Season changes the value of the Golden Triangle. Winter makes the pool, spa and restaurants central; spring and early autumn reward terraces and walking. In fashion weeks and major fairs, traffic and public-space pressure rise sharply. Guests who want the flowers without the audience should enter the lobby early, then spend the day beyond the eighth arrondissement. George V excels as an impeccably resourced base, not as a reason to remain inside."
  ]}],
  "four-seasons-bali-sayan": [{ heading: "The valley dictates the pace", body: [
    "Sayan's villas descend through dense planting toward the Ayung River, and the steep, humid terrain is central to the experience. Lower villas hear more water and feel enveloped by jungle; higher positions are closer to reception and may open wider views. Buggy service reduces the effort but does not erase steps, slopes or slick paths after rain. Guests with mobility concerns should request a precise route and avoid choosing solely from a romantic aerial photograph.",
    "The resort's strongest activities use the landscape rather than decorate it: river rafting, guided rice-field walks, temple visits and wellness in the Dharma Shanti space. Families can be absorbed by the children's programme, while couples should protect at least one unscheduled afternoon around a private pool. Ubud traffic is now substantial, so repeated town journeys can consume the calm the hotel is designed to create. Combine one deliberate excursion with time in the valley instead of attempting a daily commute."
  ]}],
  "gritti-palace-venice": [{ heading: "Season can transform the same canal room", body: [
    "Winter gives the Gritti mist, quieter calli and more room at breakfast, but acqua alta and abbreviated restaurant schedules require preparation. Summer supplies terrace life and relentless boat traffic. Spring and autumn offer the best balance, though Biennale openings and festivals can make the city as compressed as August. Rates should be read against Venice's calendar, not simply the weather forecast.",
    "A private transfer from airport or station is expensive but solves the difficult first ten minutes: luggage moves from boat directly through the palazzo landing. Vaporetto travel is far cheaper and often more enjoyable once settled. Guests prone to seasickness or unable to manage steps should discuss every transfer in advance. In Venice, logistics are not separate from luxury; making movement graceful is one of the services being purchased."
  ]}],
  "jai-mahal-palace-jaipur": [{ heading: "A resort garden in the middle of a working city", body: [
    "Jai Mahal's 18 acres create lawns, paths and a pool behind the palace façade, valuable for families and longer Jaipur stays. They also make the property feel more like an urban resort than a small heritage house. The 100-room inventory—94 rooms and six suites—means breakfast and weddings can introduce real volume. Ask about event dates and the location of the assigned room if quiet matters more than proximity to the lobby.",
    "The address is west of the old city rather than inside its walls. Hawa Mahal, City Palace and Amber Fort require a car and Jaipur traffic can turn a short map distance into a long return. This separation is welcome after sightseeing but less compelling for guests who want to step directly into bazaars. Book for space, pool time and Taj's experienced family service; choose a smaller haveli if intimacy and neighbourhood texture outrank facilities."
  ]}],
  "w-koh-samui": [{ heading: "The island's weather has two personalities", body: [
    "Koh Samui's rain pattern differs from Phuket's, with the wettest stretch often arriving later in the year. A storm can flatten the famous sea view, roughen the beach and move dinner indoors; it can also leave the hillside intensely green. Flexible travellers gain value in shoulder months, but a honeymoon built around uninterrupted sun should be timed conservatively and insured.",
    "All 74 villas have pools, which makes the entry category unusually complete. Higher hillside villas receive the broadest horizon and more buggy dependence; beachfront choices add immediacy but less privacy from passing guests. The W's music, bars and playful design are intentional, not background noise. Couples wanting sociability will enjoy the rhythm. Those seeking Thai stillness should compare it honestly with the island's quieter east and south coasts."
  ]}],
  "explora-patagonia": [{ heading: "The building is a piece of expedition equipment", body: [
    "Explora's position beside Lake Pehoé eliminates a daily transfer into Torres del Paine and turns changing weather into the view from bed. Rooms are deliberately plain beside the landscape: warm timber, excellent bedding, large windows, no television. Salto Chico rooms look toward the waterfall; Cordillera Paine rooms frame the massif. The latter is the postcard, but the waterfall's sound and movement can be the more absorbing companion.",
    "The stay is sold around guided explorations, not à-la-carte sightseeing. Each evening, guides help match walks, rides and overland routes to weather and ability. That planning is the product. Strong hikers should resist chasing only the longest route; an easy lakeshore day can reveal birds and geology missed at speed. Wind closes plans, snow can arrive out of season and the park's distances remain immense. Four nights is the minimum at which contingency stops feeling like loss."
  ]}],
  "the-datai-langkawi": [{ heading: "Rainforest etiquette is part of the stay", body: [
    "Long-tailed macaques, dusky leaf monkeys, hornbills and monitor lizards move through the property because the forest was not cleared away from it. Doors should be locked, food kept inside and animals never fed. The Nature Centre and resident naturalists turn these rules into understanding through canopy walks, beach walks and night excursions. A room's greatest amenity may be the moment wildlife crosses the balcony, provided the encounter remains on the animal's terms.",
    "Canopy rooms sit near the main building; rainforest villas intensify seclusion and buggy reliance; beach villas exchange forest immersion for sand and private pools. The curved Datai Bay is calm and beautiful, though jellyfish, rain and seasonal sea conditions are natural variables. Golf at Els Club, the spa and several restaurants add resort breadth, but the decision should remain ecological: choose the room that places the preferred landscape at the door."
  ]}],
  "umaid-bhawan-jodhpur": [{ heading: "The palace is shared with a living household", body: [
    "Only part of Umaid Bhawan operates as a Taj hotel; another part remains the royal family's residence and a third houses the museum. The division gives the building authenticity and unavoidable boundaries. Some domes, corridors and lawns visible in photographs are not guest spaces. The 71 hotel rooms and suites occupy Art Deco interiors that can feel more 1930s Europe than storybook Rajasthan, an important distinction from the medieval Mehrangarh Fort visible across the city.",
    "Palace Rooms provide the entry experience, while Historical and Royal suites add proportion and stronger narrative detail. Ask about wing, view and distance: the building is monumental. Dinner at Risala is formal; Pillars uses the colonnade and garden; the trophy bar supplies the period-piece drink. Jodhpur deserves at least a full day outside. The palace becomes richer after the fort, old city and markets have supplied the context that its lawns intentionally withhold."
  ]}],
  "nihi-sumba": [{ heading: "Remoteness needs planning, not romance alone", body: [
    "Most guests reach Sumba on a domestic flight from Bali and continue by a substantial road transfer; schedules, baggage limits and weather can disturb the smoothest itinerary. Leave a buffer before an international departure and bring essential medication in hand luggage. Once at the resort, the isolation is productive, but it should never be mistaken for effortless access.",
    "Villas differ dramatically in beach access, elevation, pool size and number of bedrooms. Surfers should discuss Occy's Left and ability requirements before assuming the famous wave belongs to every stay; numbers are controlled and conditions rule. The Spa Safari involves a trek to Nio Beach followed by treatments in open pavilions, while horse experiences range beyond the cinematic gallop. Nihi is most responsible when the Sumbanese staff, foundation work and island culture are treated as central, not supporting scenery for adventure."
  ]}],
  "w-goa": [{ heading: "Vagator is not generic Goa", body: [
    "The hotel occupies a steep edge above Vagator, close to the Chapora Fort and North Goa's nightlife rather than the broad, quiet sands of the south. Internal buggies are useful and steps are unavoidable in places. Sea-view rooms and chalets can be far apart, so families, mobility-limited guests and light sleepers should ask for a map before accepting an upgrade that increases distance.",
    "Restaurant and bar operations shift with season and maintenance; RockPool, the cliffside headline venue, has had a temporary closure listed by the hotel. Verify its status and any events for the actual dates, because a guest booking the W for sunset energy would feel that absence. Spice Traders and The Kitchen Table provide alternatives, while the spa and pools keep rainy days viable. This is Goa at extrovert volume—excellent for groups, less natural for a silent beach retreat."
  ]}],
  "pashan-garh-taj-safari": [{ heading: "Safari quality depends on the park, not the thread count", body: [
    "Panna Tiger Reserve is beautiful, less trafficked than several better-known Indian parks and home to a recovered tiger population, but sightings remain chance. Drives are controlled by park permits, assigned zones and government schedules rather than the lodge. Secure permits as early as possible, provide correct identification and avoid an itinerary that treats a tiger as a guaranteed room amenity.",
    "The 12 stone cottages are inspired by dry-stacked local houses and spread through scrub woodland. Their privacy also means escorted walks after dark, insects and wildlife close to the path. Meals may move between deck, bush and private settings, yet early starts dictate the real rhythm. Two nights offer only a pair of serious opportunities; three or four allow a quiet drive, a birding walk and time to understand conservation beyond the headline cat."
  ]}],
  "rambagh-palace-jaipur": [{ heading: "A palace that is also Jaipur's drawing room", body: [
    "Rambagh hosts weddings, dinners, visiting dignitaries and local celebrations with the same confidence it gives resident guests. That social life is part of the attraction and the principal threat to tranquillity. Ask about large functions, lawn use and music before choosing a courtyard or garden-facing room. When the peacocks and fountains have the grounds to themselves in the morning, the scale feels generous rather than ceremonial.",
    "Rooms vary between restored palace spaces and later configurations; historical association does not always produce the most practical bathroom or quietest night. A suite can be splendid for receiving guests and excessive for a couple out all day. Steam, Suvarna Mahal and the Polo Bar each stage a different version of royal nostalgia. Enjoy one formal meal, then leave for Jaipur's markets and contemporary restaurants so the palace remains a perspective on the city, not its substitute."
  ]}],
  "peninsula-hong-kong": [{ heading: "The harbour view now comes with a tower decision", body: [
    "The original 1928 building contains the ceremonial lobby and lower, more classical rooms; the 1994 tower rises behind it with higher harbour perspectives and a rooftop helipad. A tower room generally wins for the view, while the original building wins for historical proximity. Renovations have integrated discreet technology, but dimensions and outlook still vary. Confirm whether the room sees Victoria Harbour directly or at an angle past neighbouring buildings.",
    "The fleet of Rolls-Royces and helicopter transfer are famous, yet the MTR entrance and Star Ferry nearby are the more useful luxuries. Felix remains Philippe Starck's dramatic dining room above the harbour; Gaddi's carries French formality; Spring Moon serves Cantonese food; afternoon tea fills the lobby with a queue. Residents should experience the spectacle once and then use Hong Kong's transport and appetite. The Peninsula is strongest as an exceptionally located base, not a museum of its own traditions."
  ]}],
  "khyber-himalayan-gulmarg": [{ heading: "Snow makes the hotel—and complicates it", body: [
    "Winter access to Gulmarg depends on road, weather and local vehicle rules. Flights into Srinagar can be delayed, the final drive lengthens in snow and luggage may change vehicles before the hotel. Build buffer into both directions, carry proper footwear and do not place a non-refundable international connection immediately after checkout. The inconvenience is inseparable from the landscape guests have come to see.",
    "The Khyber has 85 rooms and cottages, but not every category faces the Apharwat peaks. Valley or forest outlooks can be quieter and less costly; mountain rooms deliver the expected drama when cloud permits. Skiing at Gulmarg is not a manicured European resort system: lift status, avalanche risk, guides and equipment require active planning. Non-skiers have the pool, spa and snow landscape, though a long stay can feel enclosed when storms close the mountain."
  ]}],
  "one-and-only-cape-town": [{ heading: "A city resort, with city-resort trade-offs", body: [
    "The marina position places the V&A Waterfront at the door and makes family logistics unusually easy: restaurants, boats, aquarium and shopping require little negotiation. It is less atmospheric than sleeping in the City Bowl and further from the neighbourhood life of Kloof Street or Bree Street. Road access to the Atlantic beaches is straightforward until Cape Town traffic and wind decide otherwise.",
    "Marina Rise rooms are closest to restaurants and public energy; Island rooms sit around waterways near the spa and feel more residential. ROOI focuses on South African ingredients, Isola handles poolside Mediterranean meals and Vista occupies the lobby beneath Table Mountain views. The island spa and large pool justify the resort label, but wind can cool an otherwise bright day quickly. Pack layers, reserve a mountain-facing room only if the premium survives cloud, and use the concierge to plan around—not against—the weather."
  ]}],
  "oberoi-udaivilas-udaipur": [{ heading: "Lake travel is part of the architecture", body: [
    "The most satisfying arrival crosses Lake Pichola by boat and approaches the domes through gardens, turning a transfer into the opening scene. Water levels and local operations can change the route, so road access remains the dependable alternative. Once inside, courtyards and long axes produce substantial walking; buggies assist, but guests with limited mobility should request a room close to the core facilities.",
    "Premier Pool View rooms look across water and garden, while semi-private pool rooms open to long shared pools rather than a wholly private plunge. That distinction matters for both privacy and families. The palace-city sights lie across the lake and deserve time, even though the resort makes departure difficult. A three-night rhythm works: city and palace on one day, countryside or boat on another, and one protected day allowing the pools and terraces to become more than scenery."
  ]}],
  "amangiri-utah": [{ heading: "The itinerary extends far beyond the pool", body: [
    "The famous rock-embracing pool is only the still centre of a 900-acre property with more than 12 miles of marked trails. Guided hikes, via ferrata routes, canyon excursions, horse rides and Lake Powell outings can turn the stay athletic quickly. Some experiences cost extra and require weather windows, minimum ages or firm footing; confirm difficulty and pricing rather than letting cinematic photographs write the schedule.",
    "Amangiri's main pavilion has 34 suites, while Camp Sarika sits apart with ten tented pavilions and its own pool and restaurant. The camp offers privacy and immediate desert immersion; the main resort provides easier access to spa, dining and the architectural icon. Transfers between them are short but meaningful. Three nights permit one major expedition and recovery; four make room for weather. The desert is the luxury, and over-programming is the fastest way to miss it."
  ]}],
  "belmond-hotel-caruso": [{ heading: "The room should support the terrace life", body: [
    "Caruso's interiors are comfortable and carefully maintained, but the decisive spaces are outside: pool, gardens, restaurant terrace and the paths descending through Ravello. A room without balcony or strong outlook may be entirely lovely and still feel like the wrong economy. Ask how private the terrace is, whether the sea view clears planting and how many stairs separate it from breakfast.",
    "Families should note that cliffside romance and young children require vigilance, while couples need to know when weddings will occupy the principal terraces. The hotel's boat and shuttle make coastal exploration possible, though summer timetables and road traffic are never fully controllable. Ravello's concert calendar can add a memorable evening; it can also compress restaurant demand. Check events before dates, then let the stay breathe around one or two of them."
  ]}],
  "hotel-du-cap-eden-roc": [{ heading: "A seasonal hotel demands seasonal questions", body: [
    "Eden-Roc closes for part of the year, and opening-week or late-season stays may not present the same restaurant hours, water temperature or social tempo shown in midsummer photographs. Cannes Film Festival dates amplify both glamour and disruption. Ask which waterfront restaurants, boats, children's activities and spa facilities will operate for the exact week, particularly if the room rate assumes a fully animated resort.",
    "The property suits accomplished swimmers better than tentative beachgoers: sea access is from rock platforms and ladders, while the pool supplies controlled water. Cabanas have their own hierarchy and cost. Families gain gardens and activities but should discuss room placement; couples seeking seclusion should look beyond the central pool axis. The hotel is at its best when guests accept ritual—dressing for dinner, reserving the same place by the water, allowing afternoons to repeat—rather than chasing the Côte d'Azur by car."
  ]}],
  "oberoi-new-delhi": [{ heading: "Air and calm are not minor amenities in Delhi", body: [
    "The rebuilt Oberoi's advanced filtration system is a practical luxury during polluted months, particularly for children and sensitive travellers. It cannot change outdoor air, and guests should still check current conditions before exercise or long sightseeing days. The indoor and outdoor pools, spa and well-sealed rooms make the hotel unusually capable of functioning as a refuge when heat, dust or winter smog intervene.",
    "Golf-course and Humayun's Tomb views distinguish the rooms from Delhi's more inward-facing palace hotels. The address is excellent for central and south Delhi but not walkable in a meaningful tourist sense; cars remain essential. 360° handles all-day dining, Omya gives Indian cooking a polished stage and Baoshuan brings a rooftop Asian menu. The hotel can feel businesslike beside older grande dames, yet its clarity, air quality and compact service are precisely why many repeat guests choose it."
  ]}],
  "fogo-island-inn": [{ heading: "The stay begins with a transport calculation", body: [
    "Fogo Island is reached by ferry from Farewell or by limited air service, and Atlantic weather can alter either. The inn helps coordinate transfers, but a buffer night before a critical flight is prudent. Once there, every booking includes a community host connection, which turns settlements, fishing stages and local stories into more than picturesque background. The island is inhabited and working; guests are visitors to that life, not owners of an empty edge.",
    "All 29 rooms face the ocean, though corner orientation, soaking tubs and wood-burning stoves vary. The architecture is stark from outside and unexpectedly warm within, with furniture and quilts made through local collaborations. Meals are central because alternatives require distance and planning; the kitchen uses preserved, foraged and island-grown ingredients with seasons setting real limits. The community-owned model and economic mission deserve attention, but virtue does not excuse the high price. What justifies it is the combination of design, hosting and a place interpreted with unusual intelligence."
  ]}],
  "the-lodhi-new-delhi": [{ heading: "Timing matters more than the map suggests", body: [
    "The Lodhi's central position is genuinely useful, but Delhi journeys are governed by the hour. An early visit to Humayun's Tomb can take minutes; the same route after breakfast may be slowed by school and office traffic. Build sightseeing geographically—Nizamuddin and Lodhi Gardens together, Old Delhi on another day—then return before the roads harden into evening congestion. The hotel's cars are excellent and priced accordingly; app taxis are cheaper but less seamless at the gate.",
    "The plunge-pool room is the signature, not an automatic upgrade. In winter, shade and water temperature affect its appeal; in summer, privacy and direct sun matter. Ask about aspect, heating and sightlines from neighbouring floors. A well-positioned standard room with balcony can be the wiser buy when most hours belong to the city. The Lodhi earns its rate through choices—space, exercise, food, retreat—but only when the chosen category matches how the day will actually be lived."
  ]}],
  "the-leela-palace-new-delhi": [{ heading: "What ceremony costs—and when it is worth it", body: [
    "The Leela's abundance works brilliantly for a wedding party, diplomatic visit or first journey to India, when multiple restaurants, a deep concierge bench and an exceptionally comfortable room reduce uncertainty. The same machinery can feel excessive on a short solo stay. Royal Club access is valuable when breakfast privacy, pressing and evening drinks replace outside plans; it is less persuasive for guests who leave after coffee and return after dinner.",
    "Delhi's seasons sharpen the decision. The rooftop pool is glorious in October and early spring, often too cold for long winter swims and punishing at midsummer midday. Wedding season can fill the driveway and shift the mood of public rooms. Ask about large functions, pool temperature and the exact club benefits for the booked rate. This is a palace conceived around occasion; choosing the right week allows its theatre to feel generous rather than crowded."
  ]}],
  "taj-mahal-palace-mumbai": [{ heading: "How to inhabit an icon without being consumed by it", body: [
    "The Palace Wing's history can tempt guests into accepting any room assigned under its dome. Do not. Floor plans, window size and harbour angle vary, and some lower rooms encounter more courtyard or public-space noise. Ask for the Gateway in view, specify whether a bath matters and request distance from lifts if sleep is fragile. The Tower is sometimes the more rational answer for families who value consistency and connecting rooms over decorative provenance.",
    "Monsoon changes the hotel beautifully: ferries vanish into grey water, rain drums on the harbour and Colaba becomes harder to walk. It also disrupts boats to Elephanta and exposes traffic delays. In drier months, reserve dawn for the Gateway and the Fort district before heat and crowds build. The Taj should frame Mumbai, never replace it. Its best service is not keeping the city away but making the city's immense energy easier to enter and return from."
  ]}],
  "the-oberoi-mumbai": [{ heading: "A precise choice for a divided city", body: [
    "Mumbai now asks travellers to choose a geography as much as a hotel. Nariman Point is excellent for the courts, Fort, Colaba, galleries and Marine Drive; it is a punishing daily base for Bandra Kurla Complex or northern studios. Sea Link and coastal-road improvements may change a journey without making it predictable. Put every fixed appointment on a map before booking, and let the hotel organise airport timing with a margin that feels excessive until it does not.",
    "The Oberoi's restraint also suits some emotional occasions better than others. It is superb after a long flight, during demanding work or for travellers who value privacy over lobby theatre. A celebratory first visit may find the Taj more visibly romantic. Here, the reward arrives cumulatively: clothes returned perfectly, a breakfast remembered, the same sea changing colour beyond the glass. Luxury is expressed as continuity rather than display."
  ]}],
  "capella-bangkok": [{ heading: "The river villa is a mood, not merely a category", body: [
    "Capella's seven villas sit unusually close to the Chao Phraya, with a small garden, verandah and plunge pool placing boats almost at eye level. That immediacy also reduces visual privacy; river traffic and neighbouring outdoor spaces remain part of the scene. Guests who want water without exposure may prefer a high Verandah Suite, gaining a larger horizon and leaving the pool to the hotel's beautifully planted riverfront.",
    "Charoenkrung rewards an early walk before heat takes control. Talat Noi, galleries, old shophouses and street food provide the texture a self-contained river resort cannot manufacture. Cross-town journeys to Sukhumvit can be slow, so organise days by district and use the hotel boat where it genuinely helps. Capella's Culturists are most valuable when asked to simplify rather than decorate the itinerary. The city has enough spectacle; this hotel succeeds by creating clarity beside it."
  ]}],
  "weligama-bay-marriott": [{ heading: "Choose it for the bay, then leave the resort at least once", body: [
    "The 199-room scale is visible at breakfast and around the pool during school holidays. Higher ocean-facing rooms protect the view and soften activity below; lower floors feel closer to the surf but hear more of the terrace. Families should ask about connecting rooms, children's programming and event dates, while dedicated surfers may prefer direct beach access over a suite. The bay's forgiving waves suit lessons, not experienced riders chasing Sri Lanka's sharper breaks.",
    "Mirissa lies close for harbour departures, though whale-watching ethics depend heavily on the operator: choose a boat that limits pursuit and respects approach distances. Galle Fort merits an unhurried half-day, and smaller restaurants along the south coast prevent the buffet from becoming the entire culinary memory. Monsoon patterns differ across the island, so check south-coast conditions for the actual month. Marriott makes Weligama easy; the best stay uses that ease to explore rather than remaining behind the resort gates."
  ]}],
};
