import type { BestHotelEntry, BestHotelsList } from "../best-hotels";

const pick = (rank: number, name: string, location: string, bestFor: string, style: string, description: string, caveat: string, officialUrl: string, reviewSlug?: string): BestHotelEntry => ({ rank, name, location, bestFor, style, description, caveat, officialUrl, reviewSlug });

export const octoberBestHotelsLists: BestHotelsList[] = [
  {
    slug: "hong-kong", destination: "Hong Kong", country: "Hong Kong SAR",
    title: "The 10 Best Hotels in Hong Kong", updated: "October 2026", updatedISO: "2026-10-04",
    dek: "Ten distinct ways into Hong Kong, from a Kowloon harbour icon and a discreet Admiralty sanctuary to a thoroughly useful city hotel above Pacific Place.",
    heroImage: "/hotels/peninsula-hong-kong.jpg", heroAlt: "The Peninsula Hong Kong in Tsim Sha Tsui",
    intro: [
      "Hong Kong is especially unforgiving of the lazy hotel shortlist. A perfect harbour photograph says little about the journey you will make each morning, the scale of the lobby you want to return to, or whether the view even belongs to the room you have booked. The city's great hotels sit in quite different versions of Hong Kong: the layered streets of the island, the ceremonial Kowloon waterfront and quieter pockets that reward a return visit. Choose the experience first; the ranking can only take you so far.",
      "Our ten choices are deliberately varied. The upper ranks are not simply the most expensive: they make the strongest case for a particular stay, whether through service, architecture, position or the way a room connects you to the city. We have included a newer, more accessible-scale Wan Chai address alongside the grande dames because a useful list should help you choose, not merely admire. Where THL has a full hotel review, follow that link for the longer argument; where it does not, consult the hotel's own room categories and current policies before booking.",
    ],
    planning: [
      { heading: "Island or Kowloon?", body: "For an itinerary concentrated on Central, Admiralty or Wan Chai, an island base makes the daily rhythm easier. Tsim Sha Tsui suits travellers who want the famous island skyline across the harbour and a Kowloon-centred trip. Neither bank is inherently more authentic. Decide which crossing you would enjoy making for pleasure, rather than making twice a day from necessity." },
      { heading: "What does a view buy?", body: "Harbour, partial-harbour, city and mountain categories are not poetic synonyms. Ask the hotel what the exact room category overlooks and whether the photographed view is guaranteed. If you will leave at dawn and return at night, a lower-priced room in the right hotel may improve the trip more than a premium aspect you scarcely occupy." },
      { heading: "How long to stay?", body: "Three nights gives a first visit breathing room: one day for the island, one for Kowloon and one without an obligation to collect landmarks. Add time for an outlying excursion or a slower, food-led return. On a short trip, change hotels only if the second address radically changes the experience; otherwise a checkout will cost more than it gives." },
    ],
    hotels: [
      pick(1, "Rosewood Hong Kong", "Victoria Dockside, Tsim Sha Tsui", "A complete luxury world by the harbour", "Contemporary waterfront hotel", "Rosewood has enough conviction in its design and service to feel like a destination without losing sight of the city outside. The Victoria Dockside setting brings the water and Hong Kong Island into the stay; rooms, dining and Asaya give the building serious internal range. Its scale matters: this is not an intimate house, but a hotel that can hold a long weekend even when the weather closes in. We would choose it for a celebratory trip with time to use more than the bedroom. Ask about the exact aspect and floor rather than assuming the word harbour describes every room equally.", "A Kowloon address requires a crossing for island-heavy days. The property's breadth and price make less sense if you plan to be out from breakfast until midnight.", "https://www.rosewoodhotels.com/en/hong-kong"),
      pick(2, "The Upper House", "Pacific Place, Admiralty", "Quiet design and attentive privacy", "Design-led urban retreat", "The Upper House offers an answer to Hong Kong's constant motion that does not involve leaving town. Its upper-floor rooms and public spaces create a sense of removal while Pacific Place and Admiralty's connections keep the city immediately useful. The design has enough restraint to let materials, light and proportion do the talking; Salisterra gives the hotel a social table without turning the rest of it into a scene. It is a compelling choice for repeat visitors, couples and anyone who wants their hotel to be a refuge rather than another spectacle. The comparison with the neighbouring JW Marriott is about mood, not superiority.", "Its discretion comes with fewer large-hotel facilities. If a substantial pool-and-restaurants operation is essential, look next door or elsewhere.", "https://www.thehousecollective.com/en/the-upper-house", "upper-house-hong-kong"),
      pick(3, "The Peninsula Hong Kong", "Salisbury Road, Tsim Sha Tsui", "A grand historic Hong Kong arrival", "Heritage landmark with modern tower", "The Peninsula's distinction is not only age or its famous frontage. It is the confidence with which an established hotel can still make the day feel like an occasion. The location places the island skyline across the water, while its public rooms and restaurants have a gravity that a newer luxury tower cannot simply buy. This is the right booking when ceremony is part of the pleasure and the hotel is a principal event, not merely the place you keep your luggage. Ask whether the available room sits in the original building or the newer tower; the names may sound similar, but the experience differs.", "High rates do not guarantee the desired view. The grand public profile may feel too formal if you prefer a small, almost anonymous hotel.", "https://www.peninsula.com/en/hong-kong/5-star-luxury-hotel-kowloon", "peninsula-hong-kong"),
      pick(4, "Mandarin Oriental, Hong Kong", "Connaught Road, Central", "An established island institution", "Classic city grand dame", "For travellers who want to belong to Central rather than admire it from across the water, Mandarin Oriental remains a persuasive address. Its strength is the accumulated habit of hospitality: restaurants, bars and a rhythm that suits guests with complicated days as well as those who have come simply to enjoy the hotel. It offers a more city-embedded idea of luxury than the resorts of the Kowloon waterfront. Book it with a plan to use the district—perhaps an early walk and a return for a drink—rather than treating its reputation as an end in itself. Room aspects and categories deserve careful comparison.", "A classic institution has a different energy from a new design hotel. Confirm whether your room has the outlook and degree of quiet you expect.", "https://www.mandarinoriental.com/en/hong-kong/victoria-harbour"),
      pick(5, "Four Seasons Hotel Hong Kong", "IFC, Central", "Waterfront ease with serious dining", "Contemporary city hotel", "Four Seasons makes a strong case for visitors who want Central access and the harbour in the same stay. The connection to IFC is a practical advantage; the pool and dining, including Caprice, give you reasons not to rush away at the first free hour. Where some city hotels use the skyline as a backdrop and little more, this one is structured to help you enjoy it across a longer day. It is particularly good for a trip that mixes business with a proper weekend. Compare room categories precisely: a building with a remarkable location does not make every bedroom's outlook identical.", "The integrated commercial setting will not please everyone. Dining reservations and room-view supplements can materially change the total cost.", "https://www.fourseasons.com/hongkong/"),
      pick(6, "Regent Hong Kong", "Salisbury Road, Tsim Sha Tsui", "The harbour as a room-length event", "Contemporary waterfront revival", "Regent is for the traveller who regards the water as a central character, not an optional backdrop. Its position on the Tsim Sha Tsui edge brings the island's towers into close conversation with the interiors, and the renewed hotel has the confidence to frame rather than compete with them. The dining and public spaces are substantial enough for a celebratory stay, yet the essential purchase remains a well-chosen room and its relation to the harbour. Book the exact view and configuration rather than relying on the property's general reputation. For a Kowloon evening, it is a compelling place to finish the day.", "A harbour-facing room can command a substantial premium. Island-centred itineraries still require frequent crossings.", "https://hongkong.regenthotels.com/"),
      pick(7, "JW Marriott Hotel Hong Kong", "Pacific Place, Admiralty", "A convenient island base that delivers", "Full-service international hotel", "The JW's best argument is made after the first day, when the convenience of Pacific Place and Admiralty has already saved a journey or two. Its restaurants include Cantonese cooking at Man Ho and poolside seafood at Fish Bar; an outdoor pool and substantial public spaces make a free afternoon easy to fill. Zinnia's full THL review explains why this is more than a merely efficient choice. It suits a trip that asks the hotel to be capable at many things without turning every interaction into theatre. Select city, mountain or harbour views consciously—those room categories are different purchases.", "The public spaces have a busy large-hotel rhythm. It does not offer the near-residential quiet of The Upper House, although they share the wider address.", "https://www.marriott.com/en-us/hotels/hkgdt-jw-marriott-hotel-hong-kong/overview/", "jw-marriott-hotel-hong-kong"),
      pick(8, "The Murray, Hong Kong", "Cotton Tree Drive, Central", "Architecture and a more composed Central", "Modernist landmark hotel", "A former government building given a second hotel life, The Murray turns an unusual piece of Hong Kong's modernist inheritance into an address with real visual identity. Its position near Hong Kong Park offers a calmer approach to Central than the busiest waterfront blocks. The architecture is not a decorative theme: the building's geometry and the way it meets the street shape the stay. Choose it if you like hotels that reward looking twice, and if your days are mainly on the island. The room decision is less about a postcard harbour frame than about the space, light and layout you will actually inhabit.", "Do not book expecting the immediate waterfront outside the door. Ask about the route to your specific appointments and the outlook from the available category.", "https://www.niccolohotels.com/en/the-murray-hong-kong"),
      pick(9, "The Hari Hong Kong", "Lockhart Road, Wan Chai", "A smaller, more social city stay", "Contemporary neighbourhood hotel", "The Hari shifts the register from grand hotel to lively urban address. Tara Bernerd's interiors, Lucciola and Zoku give it an identifiable personality, while Wan Chai outside supplies the mixed, active streets that many visitors miss when they remain inside the luxury-hotel circuit. It is a good choice for a return visit or a short trip built around going out rather than withdrawing. Its smaller room scale is part of the equation: spend on the right category if you intend to work or linger in the room. If not, the neighbourhood and public spaces may be the more important purchase.", "Entry rooms are compact by Hong Kong luxury standards. Discuss street exposure and sound if early nights are important.", "https://www.thehari.com/hong-kong/"),
      pick(10, "Hopewell Hotel", "Queen's Road East, Wan Chai", "A newer, substantial Wan Chai base", "Large contemporary city hotel", "Hopewell earns a place because not every Hong Kong stay needs a century of mythology or a theatrical view. It offers a substantial contemporary base in Wan Chai, a district with texture and useful connections beyond the obvious waterfront circuit. The appeal is a straightforward one: enough hotel infrastructure to support varied travellers, and a location that encourages exploration rather than perpetual retreat. Our full review makes the case for its strengths and its less glamorous compromises. It is particularly worth comparing when rates at the best-known grande dames make the hotel budget disproportionate to the time you will spend in the room.", "This is a sizeable operation, not a boutique house. Check the room's actual aspect and the distances to the streets or stations you intend to use.", "https://www.hopewellhotel.com/", "hopewell-hotel-hong-kong"),
    ],
    faq: [
      { question: "Where should a first-time visitor stay in Hong Kong?", answer: "Admiralty or Central is a flexible island base if your plans are varied. Tsim Sha Tsui is stronger when the classic harbour panorama and Kowloon evenings are the main point. Choose around your actual itinerary, not a generic claim that one side is best." },
      { question: "Is a harbour-view room worth paying for?", answer: "Yes if you will spend time in the room to enjoy it, especially around dusk. Ask whether the view is full, partial or category-dependent. A better hotel in the right district can be a wiser purchase than the cheapest room carrying a vague 'harbour' label." },
      { question: "How many nights should I spend in Hong Kong?", answer: "Three nights is a useful first visit; four or five allows less pressured exploration and a trip beyond the central districts. Avoid moving hotels on a very short stay unless the second address changes the whole shape of the journey." },
    ],
  },
  {
    slug: "singapore", destination: "Singapore", country: "Singapore",
    title: "The 10 Best Hotels in Singapore", updated: "October 2026", updatedISO: "2026-10-04",
    dek: "From Raffles' courtyards to a 37-room river warehouse and Sentosa's tropical quiet, these are Singapore stays worth choosing for more than a skyline.",
    heroImage: "/hotels/raffles-singapore.jpg", heroAlt: "The historic Raffles Singapore hotel",
    intro: [
      "Singapore's finest hotels are often presented as a contest of pools, famous bars and rooftop altitude. That makes for an attractive slideshow and a less useful booking decision. The city contains several very different holidays in a compact space: museums and history around the Civic District, the bright spectacle of Marina Bay, smaller river addresses, the shopping momentum of Orchard and the deliberate separation of Sentosa. A room can be excellent and still belong to the wrong itinerary.",
      "These ten properties make distinctive cases for staying in them. We have valued character and a reason to return between outings, but also the ordinary practicalities: how the neighbourhood works, whether the public areas suit the traveller, and what a higher room category actually buys. The order is an editorial judgement, not a claim that Raffles is the right answer for a Sentosa family holiday or that an intimate warehouse replaces a full-service business hotel. Read the caveats as carefully as the praise; they are often where your own best choice becomes clear.",
    ],
    planning: [
      { heading: "City or island?", body: "Sentosa is a destination-within-the-destination. Book it when you want to spend meaningful time at the property, not as a cheaper substitute for a central hotel. For a short first visit built around museums, restaurants and neighbourhoods, a city base generally makes better use of the hours. With a longer trip, a city-and-island split can offer a genuine change of pace." },
      { heading: "What is the view worth?", body: "A Marina Bay panorama is an experience, but room views can differ even within one hotel. Confirm the exact category and whether you will enjoy it in daylight. If your plans keep you out all day, a stronger neighbourhood or more comfortable room may matter more. Rooftop pools, resident-only facilities and public observation decks have separate access rules." },
      { heading: "How many nights?", body: "Three nights allows one museum-and-neighbourhood day, one bay-and-river day and a third shaped around food, gardens or the hotel itself. Longer stays can absorb Sentosa without making the island feel like a rushed side trip. If travelling with children, compare bed layouts and connecting-room guarantees as closely as the property's photographs." },
    ],
    hotels: [
      pick(1, "Raffles Singapore", "Beach Road, Civic District", "A hotel with its own sense of occasion", "Historic all-suite grand dame", "Raffles is the name most first-time visitors know, but its case rests on more than familiarity. The arcades, courtyards and suites let the hotel establish a slower tempo in the middle of a working city. It is a place to return to between outings, not merely to photograph from the pavement. The Long Bar is part of the folklore; the greater pleasure is the room to inhabit the property without haste. Choose it for a milestone stay with time to enjoy the architecture and the surrounding Civic District. It has the confidence of a landmark that does not need to pretend to be newly discovered.", "This is an expensive, highly visible hotel. If you value anonymity and a more contemporary rhythm, its ceremony may feel like too much of the trip.", "https://www.raffles.com/singapore/", "raffles-singapore"),
      pick(2, "Capella Singapore", "Sentosa Island", "A deliberate resort interlude", "Heritage bungalows and contemporary rooms", "Capella is the compelling answer when Singapore's city pace is exactly what you want to pause. Historic bungalows and newer accommodation sit within substantial greenery on Sentosa, creating a hotel that asks you to leave space in the itinerary. It is especially persuasive after several nights in town, when the move to the island can feel like the beginning of a second holiday. Book around the room or villa arrangement you will actually use and give the property enough time to reward the transfer. The address makes less sense as a base from which to spend every day back in the Civic District or Orchard.", "Dining outlets can change during refurbishment; verify current openings. Sentosa access and transport should be planned around your actual city commitments.", "https://capellahotels.com/en/capella-singapore"),
      pick(3, "The Fullerton Bay Hotel Singapore", "Collyer Quay, Marina Bay", "A closer conversation with the water", "Intimate waterfront city hotel", "The Fullerton Bay puts the waterfront at the centre of the stay without the scale of an integrated resort. Its position is particularly convincing for travellers who want the bay within reach at more than one hour of the day: a walk before breakfast, a return after lunch, a final look at the lights. The building's relationship to the old waterfront gives it a different weight from a new-build tower. Book it for that sense of location and a smaller hotel rhythm, not simply as another way to see Marina Bay. Ask about the precise view category before paying for a panorama.", "The most sought-after bay-facing categories cost more. A waterside location does not mean every room has the same outlook or privacy.", "https://www.fullertonhotels.com/fullerton-bay-hotel-singapore"),
      pick(4, "Marina Bay Sands", "Bayfront Avenue, Marina Bay", "Singapore at maximum spectacle", "Large integrated resort", "Marina Bay Sands is not subtle, and there is no reason to demand that it should be. The architecture, shopping, restaurants and rooftop pool make it an attraction as much as accommodation. It can be great fun for a first visit or a celebration in which the sheer scale is part of the appeal. The important distinction is between admiring the building from elsewhere and staying in it: hotel guests have access to the Infinity Pool, which is not simply a public ticketed viewpoint. Choose it with eyes open to the crowds, and spend time comparing the many room categories rather than treating the silhouette as the entire booking.", "It is an enormous resort, not a quiet boutique stay. Confirm pool access, view, tower and breakfast against the exact rate before paying.", "https://www.marinabaysands.com/hotel.html", "marina-bay-sands"),
      pick(5, "The Warehouse Hotel", "Robertson Quay", "A more personal Singapore River stay", "Converted nineteenth-century warehouses", "The Warehouse Hotel offers the opposite pleasure to the bay's megastructures. Its former warehouse buildings at Robertson Quay give the rooms and shared spaces a material story; the river neighbourhood outside invites a slower, more local-seeming routine. It is particularly good for a couple who would rather choose a restaurant on foot than navigate a giant hotel concourse. The small room count changes the service and facilities equation, so embrace its scale rather than expecting an abbreviated version of a grand resort. Ask about the particular room shape and position—historic buildings rarely produce identical spaces, and that variation is part of their appeal.", "There is less full-service infrastructure than at a large luxury hotel. Confirm any mobility requirements and ask about room noise or unusual layouts.", "https://www.thewarehousehotel.com/"),
      pick(6, "The Singapore EDITION", "Cuscaden Road, Orchard", "A contemporary social address", "Design-led city hotel", "The Singapore EDITION gives the Orchard area a more deliberate design identity than a conventional shopping-district hotel. Its public spaces and bars make it a place to meet, while the rooms offer a cleaner, quieter counterpoint. Choose it when your itinerary genuinely runs through the centre and you want the hotel to have a social life after dark. It is also a useful alternative for travellers who enjoy the polish of a large brand but want a less corporate feeling at the door. Spend a little time on the exact room category and outlook; a stylish lobby does not settle the question of how your bedroom will feel.", "Orchard convenience is not a bay view or an island retreat. If you will spend every evening at Marina Bay, compare the journey honestly.", "https://www.editionhotels.com/singapore/"),
      pick(7, "Mandarin Oriental, Singapore", "Raffles Avenue, Marina Bay", "A polished, full-service bay base", "Contemporary luxury hotel", "Mandarin Oriental gives the bay-area traveller a hotel whose argument is comfort and operational range rather than novelty. Its refreshed interiors, pool and dining make it particularly useful when the trip mixes meetings, sightseeing and time with family. It has the resources to absorb an unplanned afternoon without making the whole stay feel like a shopping-and-entertainment complex. The Marina Bay location keeps iconic Singapore close while leaving room to choose your own rhythm. As with every big view hotel, pay attention to what the specific room overlooks, and consider whether an upgrade changes the experience enough to justify the cost.", "The bay setting is lively and large-scale. Compare exact room aspects and package inclusions; a generic 'Marina' description is not a guaranteed panorama.", "https://www.mandarinoriental.com/en/singapore/marina-bay"),
      pick(8, "PARKROYAL COLLECTION Pickering", "Upper Pickering Street", "Architecture with a greener outlook", "Garden-forward city hotel", "PARKROYAL COLLECTION Pickering deserves attention for the way its planted terraces change the visual language of a central business-district hotel. The building makes a statement from outside, but the better question is whether its location suits your days. It works well for travellers moving between Chinatown, the river and meetings, and for those who want their hotel to feel less sealed off from the tropical climate. This is a substantial hotel rather than a secluded garden hideaway; its architecture is a reason to stay, not a promise of silence. Ask which facilities are open on your dates and what the selected room actually faces.", "A planted exterior does not make every room a garden room. Check the pool's current operating schedule before making it the deciding amenity.", "https://www.panpacific.com/en/hotels-and-resorts/pr-collection-pickering.html"),
      pick(9, "Artyzen Singapore", "Cuscaden Road, Orchard", "A softer Orchard stay", "Contemporary design hotel", "Artyzen gives Orchard a more residential-feeling counterpoint to the area's grand commercial hotels. Balconies and a rooftop pool are part of its proposition, but the more important distinction is its mood: less about occupying a landmark and more about having a pleasant base from which the city is easy to enter. It suits a repeat visitor or a longer stay that needs a room with a little breathing space. If the outdoor area is why you are booking, verify how it relates to your particular category and whether its outlook suits you. There is no reason to pay for a balcony you will not use.", "This is an Orchard base, not a waterfront one. Its relative intimacy may mean fewer dining choices under one roof than a mega-resort offers.", "https://www.artyzen.com/en/hotels/artyzen-singapore"),
      pick(10, "The Barracks Hotel Sentosa", "Sentosa Island", "A small heritage island retreat", "Restored military barracks", "The Barracks Hotel makes a different Sentosa argument from Capella's expansive grounds. Its restored barracks give the stay a human scale and a clear sense of historical fabric; the attraction is the idea of returning to a quieter base after using the island. Choose it for a couple who want Sentosa without an enormous resort operation, or for a longer stay in which the hotel is an intentional pause from downtown Singapore. The heritage setting is a pleasure, but it also makes practical questions about room position, stairs and privacy worth asking before booking. Those details will matter more than a broad promise of island seclusion.", "Sentosa remains separate from the central city. Ask about current transfer arrangements and whether the small-hotel facilities suit everyone travelling.", "https://www.thebarrackshotel.com.sg/"),
    ],
    faq: [
      { question: "What is the best area to stay in Singapore for a first visit?", answer: "The Civic District and Marina Bay put many major sights within convenient reach and offer very different hotel personalities. Choose the Civic District for history and a city-centred stay; choose Marina Bay when the skyline and waterfront are central pleasures. The river is a smaller-scale alternative." },
      { question: "Should I stay on Sentosa or in the city?", answer: "Choose Sentosa when the hotel and island will be main parts of the holiday. For a short, urban first visit, a city hotel makes everyday exploring easier. With enough nights, splitting the trip can make both choices work without rushing either." },
      { question: "Can non-guests use Marina Bay Sands' Infinity Pool?", answer: "The hotel describes the Infinity Pool as an amenity for registered hotel guests. Do not confuse it with public attractions elsewhere in the complex; check the current access terms when booking." },
    ],
  },
  {
    slug: "bangkok", destination: "Bangkok", country: "Thailand",
    title: "The 10 Best Hotels in Bangkok", updated: "October 2026", updatedISO: "2026-10-04",
    dek: "A river grand dame, contemporary waterside sanctuaries and sharp city addresses: ten Bangkok hotels chosen for the trip you actually want to take.",
    heroImage: "/hotels/capella-bangkok-official.jpg", heroAlt: "Capella Bangkok on the Chao Phraya River",
    intro: [
      "In Bangkok, a hotel's position is an editorial decision about the city. On the Chao Phraya, boats, temple roofs and changing light become part of the day. In Sathorn and Silom, you exchange that river rhythm for a denser urban one; around Ploenchit, the logic is proximity to modern shopping and business addresses. None is a consolation prize. The mistake is to choose a famous hotel without noticing which Bangkok it is designed to make easy.",
      "The ten below favour hotels with a clear point of view and enough substance to justify the detour back to the room. They range from a deeply established river institution to a sociable tower and a quietly contemplative garden hotel. This is an independent editorial order, not a claim that every traveller needs the same address. Look particularly at the caveats: a private pool available only to certain room categories, an upriver location or a busy urban personality can turn someone else's favourite hotel into your wrong booking. Check the exact room, not merely the hotel, before paying.",
    ],
    planning: [
      { heading: "River or city?", body: "Choose the Chao Phraya if you will give the hotel time at both ends of the day. Boats can be a pleasure and sometimes a useful route, but hotel shuttles and public services have different stops and schedules. For tightly timed meetings and shopping plans inland, a well-positioned city hotel may make the whole visit calmer." },
      { heading: "What room is it?", body: "River view, riverfront terrace, city aspect, suite and residence are materially different products. A famous property can contain them all. Ask for the exact category, floor and outdoor-space arrangement; confirm whether advertised facilities are available to all guests or only to a higher tier. The answer often matters more than an extra amenity listed on a booking page." },
      { heading: "How long?", body: "Three nights gives Bangkok a chance to become more than traffic between landmarks. Keep at least one unplanned meal and one slower afternoon. For a longer trip, a city-and-river split can change the rhythm in a useful way. For two nights, stay put unless moving hotels is itself the purpose of the journey." },
    ],
    hotels: [
      pick(1, "Mandarin Oriental, Bangkok", "Charoen Krung, Chao Phraya", "The definitive river institution", "Historic grand dame", "Mandarin Oriental has the depth of a hotel that has been part of Bangkok's river story for generations. Its appeal is not simply the old-world atmosphere of certain public rooms, but the way the property continues to operate as a serious contemporary hotel: dining, service and a sense of occasion accompany the water. It is a strong choice for a milestone visit with time to use the hotel rather than simply sleep in it. The river changes mood throughout the day; make room to see that from more than the breakfast table. Check the particular wing, room aspect and any spa transfer arrangement before assuming one photograph describes the whole property.", "The formal reputation and rates may exceed what a brief, busy city trip requires. Room and wing choice make a substantial difference.", "https://www.mandarinoriental.com/en/bangkok/chao-phraya-river", "mandarin-oriental-bangkok"),
      pick(2, "Capella Bangkok", "Charoen Krung, Chao Phraya", "A private-feeling contemporary river stay", "Riverside suites and villas", "Capella offers a different kind of river luxury: more intimate in feeling, more contemporary in language, and particularly compelling when the room itself is part of the holiday. Its accommodation faces the Chao Phraya, and the hotel's scale helps it feel less like a large public institution than some neighbours. Give the place a proper afternoon. A booking that allows only a late arrival and early departure wastes much of the reason to be here. Our full review explores the property in greater depth; the essential decision is whether the river and the hotel's composed pace are what you want from Bangkok, rather than only an impressive name on a reservation.", "Its quieter mood will disappoint travellers looking for a lively, street-level city base. Compare terraces, balconies and villa categories precisely.", "https://capellahotels.com/en/capella-bangkok", "capella-bangkok"),
      pick(3, "Four Seasons Hotel Bangkok at Chao Phraya River", "Charoen Krung, Chao Phraya", "A larger, art-filled river campus", "Contemporary waterfront hotel", "Four Seasons draws a different map of the river from Capella next door. Its courtyards, art programme, restaurants and BKK Social Club give the property a generous public life; it is a hotel in which the spaces beyond the bedroom are a major part of the stay. That makes it attractive for a group with different appetites or for travellers who want to remain entertained without leaving the grounds every evening. The river is still the organising presence, but this is not a secluded villa retreat. Ask which room category gives the aspect you want, and build enough unscheduled time into the visit to make use of the hotel's breadth.", "Scale and social energy are part of the package. A river-facing photograph should not be treated as proof of the view from the entry room.", "https://www.fourseasons.com/bangkok/"),
      pick(4, "The Siam", "Dusit, Chao Phraya", "An artful upriver escape", "All-suite riverside retreat", "The Siam is a reminder that Bangkok's river has more than one tempo. Farther upriver in Dusit, its small scale and distinctive interiors make a stay feel deliberately removed from the central hotel circuit. It is for travellers who want to see the city, then return to a place that seems to belong to another rhythm. The hotel's boat can be part of that pleasure, but confirm current operating times and where it lands before using it as the backbone of a tightly scheduled itinerary. This is a good place to book with an appetite for the hotel itself—its rooms, art and river setting—not as a merely convenient address for business across town.", "The relative seclusion is the point and the compromise. Factor in journeys to restaurants and sights outside the river corridor.", "https://www.thesiamhotel.com/"),
      pick(5, "The Sukhothai Bangkok", "South Sathorn Road", "A garden-like city reset", "Established urban sanctuary", "The Sukhothai makes a convincing case for staying away from the water. Lotus ponds and composed grounds change the mood of arrival while the hotel remains in the city's working fabric. It is particularly appealing when you have plans in Sathorn or nearby districts but still want the feeling of a retreat at the end of the day. The distinction from a river resort matters: there is no need to arrange every excursion around a boat, and the quiet is cultivated inside the urban address itself. Our preference is to leave time for the property, not to treat its gardens as decoration seen only between car and lift.", "Do not mistake a contemplative setting for a riverside location. Verify room position and planned works before booking for complete quiet.", "https://bangkok.sukhothai.com/en/"),
      pick(6, "Rosewood Bangkok", "Ploenchit", "A refined base for the modern city", "Design-forward urban hotel", "Rosewood puts contemporary Bangkok, rather than the river, at the centre of the stay. Its Ploenchit position works best for a trip whose days already run through nearby shopping, restaurants or meetings. The hotel's interiors provide the polish and sense of removal that some business-oriented addresses lack, without forcing a daily journey from the waterfront. Choose it if you want the city at useful range and an atmosphere that still feels considered after dark. As always in a tall urban building, the actual room category, floor and window matter; book those knowingly rather than treating the architectural silhouette as a guarantee about every room.", "This is not a river holiday. If boats, temple views and slow waterside mornings are essential, choose a different geography.", "https://www.rosewoodhotels.com/en/bangkok"),
      pick(7, "Park Hyatt Bangkok", "Central Embassy, Ploenchit", "Seamless city convenience", "Contemporary tower hotel", "Park Hyatt's address above Central Embassy is an advantage when Bangkok's modern centre is the organising principle of a short stay. The hotel offers an elevated, polished refuge with dining and public areas that make returning early feel worthwhile, while the city remains readily accessible below. It is a smart choice for a combined work-and-leisure visit or a trip in which shopping and appointments sit on this side of town. The design's restraint is more persuasive than an attempt to imitate a riverside resort in a tower. Compare exact views, breakfast and room layouts before paying for an upgrade; the right base is already a substantial benefit.", "An integrated retail setting is not the Bangkok of waterside shophouses. Do not choose it for a Chao Phraya-focused itinerary.", "https://www.hyatt.com/park-hyatt/en-US/bkkph-park-hyatt-bangkok"),
      pick(8, "The Standard, Bangkok Mahanakhon", "Silom", "A playful, going-out hotel", "Design-led tower", "The Standard brings a very different appetite to the Bangkok hotel scene: sociable public spaces, bold design and a high-rise address that feels tuned to the city's nights. It is an excellent fit for travellers who want a hotel with a pulse, not a private sanctuary. The dining and rooftop attractions encourage time in the building, while Silom provides a useful base for exploring beyond it. Book the room for comfort and location rather than assuming the skyline spectacle is identical from every window. A traveller whose ideal evening is silence and an early book should resist the temptation to select it solely because its design photographs are compelling.", "The energy is part of the brand. Check room placement and rooftop access conditions if noise or crowds are concerns.", "https://www.standardhotels.com/en-GB/bangkok/properties/bangkok"),
      pick(9, "137 Pillars Suites & Residences Bangkok", "Sukhumvit Soi 39", "A residential-feeling longer stay", "Suites and serviced residences", "The distinction in the name matters: suites and residences are not automatically the same booking with different dimensions. This is a good candidate for travellers who want more living space and a less conventional hotel-room rhythm in the Sukhumvit area. The property is especially attractive when a longer stay makes room layout, storage and downtime as important as a single spectacular arrival. Its rooftop pool is a famous draw, but access conditions vary by accommodation type; establish them in writing if the pool is part of the reason for paying. Bangkok's long Sukhumvit corridor also makes the exact location more important than a broad district label.", "Do not assume residence guests have the same rooftop-pool access as suite guests. Confirm category and privileges before booking.", "https://137pillarshotels.com/en/bangkok/"),
      pick(10, "Anantara Siam Bangkok Hotel", "Ratchadamri Road", "Traditional city-hotel comfort", "Established grand hotel", "Anantara Siam is useful precisely because it refuses to be another version of the fashionable river retreat. Its central Ratchadamri setting and established, more traditional hotel personality suit travellers who want restaurants, shopping and city appointments to be straightforward. The public areas have a sense of occasion without asking you to organise an entire trip around the hotel itself. Choose it for comfort and an urban rhythm, particularly if your plans are inland. A classic property should still be booked with contemporary questions: ask about the specific room category, any works, the breakfast arrangement and how the hotel handles your actual arrival time.", "The appeal is polish and city convenience, not a private villa or a river panorama. Compare updated room photographs before deciding.", "https://www.anantara.com/en/siam-bangkok/"),
    ],
    faq: [
      { question: "Is it better to stay on the river or in central Bangkok?", answer: "Choose the river when the hotel, boats and waterside atmosphere are central to the trip. Choose Sathorn, Silom or Ploenchit when your activities cluster inland and time matters. Neither is universally superior; each produces a different day." },
      { question: "Are Bangkok hotel boats a substitute for taxis or rail?", answer: "No. Boat routes and hours differ by property, and public river services have their own stops. They can make certain outings delightful or efficient, but confirm the current schedule and keep a land route for time-sensitive appointments." },
      { question: "How many nights should I spend in Bangkok?", answer: "Three nights allows the city some breathing room. Add nights if you want both an energetic urban base and a slower river stay. For two nights, changing hotels is usually less rewarding than selecting one that fits your main plans." },
    ],
  },
];
