import type { Guide, GuideSection } from "../guides";

const s = (heading: string, ...body: string[]): GuideSection => ({ heading, body });
type Revision = Partial<Guide> & { sections: GuideSection[] };
const updated = "September 21, 2026";

// Full replacements, not appended paragraphs: the old generic additions must
// not reappear below these destination-specific revisions.
export const septemberGuideRewrites: Record<string, Revision> = {
  "maldives-decoded": {
    updated, title: "The Maldives, Decoded: Choose the Island Before the Villa",
    dek: "Reef, transfer, meal plan, beach: the decisions that matter more than an overwater photograph.",
    excerpt: "How to choose a Maldives resort: compare island size, reef access, transfers, beach and overwater villas, meal plans and the real total cost.",
    heroImage: "/hotels/soneva-fushi-maldives.jpg", cardImage: "/hotels/soneva-fushi-maldives.jpg", imageAlt: "Soneva Fushi resort in the Maldives",
    sources: [{ label: "Seaplane planning and baggage", url: "https://www.transmaldivian.com/faq/" }, { label: "Visit Maldives", url: "https://visitmaldives.com/" }],
    sections: [
      s("The photograph does not choose the holiday",
        "An overwater villa is a wonderfully efficient image. It conveys privacy, warm sea and the apparent abolition of ordinary life in a single frame. It does not tell you whether the island has a beach you will enjoy, whether snorkelling requires a boat or whether dinner for a week will cost more than you expected. The most important Maldives booking decision is the island. The bedroom comes afterwards.",
        "Start with your main pleasure. A keen snorkeller should investigate current reef access and conditions. A family may care more about a manageable beach, suitable accommodation and dining flexibility. Someone travelling for seclusion should ask about villa spacing and sightlines rather than treating an aerial photograph as evidence of privacy. No island is best at everything, and the most expensive one may solve a problem you do not have."),
      s("The transfer is part of the booking",
        "Speedboat, seaplane and domestic-flight connections create different arrival days. Trans Maldivian Airways arranges resort transfers through its partner properties and operates seaplanes in daylight. That makes international flight timing consequential. Confirm the resort's current connection requirements before buying flights, including what happens if you arrive too late or weather interrupts the transfer.",
        "Ask for the transfer price in the same quote as the room. Check baggage limits separately from the allowance on your international ticket, and keep essentials in your hand luggage. Do not plan a tight onward connection on the assumption that island transport will behave like a city taxi. A beautiful arrival is still a transport operation, and it deserves a buffer."),
      s("Beach villa or overwater?",
        "A beach villa can offer shade, planting and a more natural route between room and shore. An overwater villa makes the lagoon immediate, but the deck may be exposed and the route to restaurants longer. Neither category guarantees privacy. Ask about neighbouring sightlines, public paths and whether the view faces open water, another row of villas or resort infrastructure.",
        "For families, check age policies and the details of railings, access and pool safety with the hotel. For couples, think about how you will use the room after the arrival photograph: reading outdoors, swimming, sleeping late or escaping the heat. A category that suits those hours is worth more than a famous silhouette."),
      s("Read the meal plan like a contract",
        "Half board and all-inclusive are labels, not identical products across resorts. Establish which restaurants are covered, whether reservations are required, what carries a supplement and how drinks are treated. A generous-looking package may be less useful if the meals you most want sit outside it. Conversely, a straightforward plan can make a long stay pleasantly free of arithmetic.",
        "Compare the full cost for your party over the whole stay: room, applicable taxes and fees, transfers, meals and the activities you realistically intend to book. Do not use a low-season headline rate to judge a school-holiday quotation. The most useful price is the one for your dates and needs, not the cheapest number the internet can find."),
      s("Leave something unplanned",
        "Choose enough nights to let the arrival journey recede. Moving between several resorts on a short trip often replaces leisure with packing and transfers. One well-chosen island can be more rewarding than an itinerary designed to demonstrate variety. If you do split, make the difference meaningful: perhaps a larger island with more walking space and then a smaller, more concentrated retreat.",
        "Finally, ask what the resort is doing to care for the marine environment in terms you can understand, rather than accepting a sustainability adjective. Avoid wildlife experiences built around disturbance. The Maldives is at its most compelling when the water is treated as a living place, not an amenity installed for the villa. A good booking leaves room to notice it."),
    ],
  },
  "first-safari-guide": {
    updated, title: "Your First Safari: Spend on the Guiding, Not Just the Lodge",
    dek: "Choose one landscape, allow enough nights and understand what a game drive actually involves.",
    excerpt: "Plan a first safari with practical advice on national parks versus private reserves, guiding, nights per camp, family rules and realistic expectations.",
    hotelSlugs: ["singita-sabi-sand"], heroImage: "/hotels/singita-sabi-sand.jpg", cardImage: "/hotels/singita-sabi-sand.jpg", imageAlt: "Singita accommodation in the Sabi Sand reserve, South Africa",
    sources: [{ label: "SANParks game-drive information", url: "https://www.sanparks.org/parks/kruger/what-to-do/activities/game-drives" }, { label: "Kruger visitor rules", url: "https://www.sanparks.org/parks/kruger/useful-information/vital-information" }],
    sections: [
      s("Begin with a place, not a species checklist",
        "The first safari is often planned as if wildlife were a collection of appointments. A lion at dawn, a leopard before lunch, something spectacular beside the sundowner. It is an understandable fantasy and an unhelpful contract with the natural world. Choose a landscape you are interested in, a camp whose guiding you trust and enough time to let the experience develop. Sightings are part of it, not a timetable anyone can honestly guarantee.",
        "For a first trip, three or four nights in one well-chosen camp is a sensible starting point. It gives the early starts a rhythm and avoids repeatedly spending the middle of the day transferring. A second camp should add a genuinely different environment or experience, not merely a different bathroom. More stops do not automatically create a richer safari."),
      s("National park and private reserve are different purchases",
        "A self-drive national-park visit and a guided stay in a private reserve differ in cost, independence and operating rules. Do not assume that activities advertised by one lodge are permitted everywhere. In Kruger, SANParks sets rules around roads, leaving vehicles and designated stopping places. A reserve's approach to night drives or off-road travel must be checked with that operator.",
        "Neither model is inherently the more serious way to see wildlife. Self-driving can be rewarding for travellers who enjoy planning and observation. A good guided stay adds interpretation and lets you concentrate on the landscape rather than navigation. Ask what is included, how vehicles are shared and how the operator handles crowded sightings. The ethics of a drive matter as much as the equipment on it."),
      s("The guide changes what you see",
        "A knowledgeable guide can make tracks, birds, plants and animal behaviour interesting before a large predator appears. That is the difference between a safari that depends on a trophy sighting and one that remains absorbing on a quieter drive. When comparing camps, ask about guiding qualifications, vehicle occupancy and whether your party is likely to keep the same guide during the stay.",
        "A private vehicle can be worthwhile for a family with specific needs or photographers who want to linger. It is not automatically necessary for everyone. Discuss expectations in advance: some guests want long, patient observation; others struggle with several hours seated. The best arrangement is the one that makes the experience comfortable without pressuring the guide to turn wildlife into a performance."),
      s("Understand the daily rhythm",
        "Expect early departures and a substantial interval between morning and later activities at many camps. Confirm the actual programme rather than assuming all lodges follow the same one. That middle part of the day is why a comfortable camp matters, but comfort need not mean excess. Shade, a good place to sit and the ability to rest can matter more than an elaborate suite feature.",
        "Pack for changes in temperature and conditions, not just the afternoon forecast. Ask about luggage restrictions before a small-aircraft transfer. Families should confirm minimum ages for each activity: a child accepted at a lodge is not necessarily eligible for every drive or walk. SANParks' guided-drive rules, for example, include age restrictions; private operators may use different ones."),
      s("Keep the promises realistic",
        "Arrange destination-specific health advice with a qualified travel clinician before departure, and follow the operator's safety instructions in camp and on drives. Do not use a hotel review as medical guidance or a reason to approach wildlife. Good safari planning is partly the willingness to accept rules whose purpose may not be immediately obvious to a first-time visitor.",
        "The most useful luxury is time: time to watch an animal do something ordinary, to learn why a guide has stopped, to return to a place without requiring a better photograph. Spend accordingly. A lodge can make the setting comfortable, but it cannot purchase a particular encounter. The safari becomes more memorable when you stop asking the bush to fulfil a shopping list."),
    ],
  },
  "sri-lanka-in-ten-days": {
    updated, title: "Sri Lanka in Ten Days: A Route With Room to Breathe",
    dek: "Culture, hills and the south coast—plus what to cut when the journey starts doing too much.",
    excerpt: "A ten-day, nine-night Sri Lanka route covering the Cultural Triangle, Kandy, the hills and Ahangama, with realistic choices and seasonal caveats.",
    hotelSlugs: ["abode-by-the-beach-sri-lanka", "weligama-bay-marriott"], heroImage: "/hotels/abode-by-the-beach-official.webp", cardImage: "/hotels/abode-by-the-beach-official.webp", imageAlt: "Rock Suite at Abode by the Beach on Sri Lanka's south coast",
    sources: [{ label: "Sri Lanka's cultural heritage", url: "https://srilanka.travel/cultural_heritage" }, { label: "Beach regions and seasons", url: "https://www.srilanka.travel/pristine-beach-holidays" }],
    relatedReading: [{ label: "Abode by the Beach review", url: "/hotels/abode-by-the-beach-sri-lanka" }],
    sections: [
      s("Nine nights, not nine different hotels",
        "Sri Lanka encourages overconfidence. The map looks compact, the possibilities are seductive and suddenly a ten-day holiday contains ancient cities, a mountain railway, two national parks and three beaches. The result can be a sequence of arrivals with little time to inhabit any of them. A better trip chooses its priorities and accepts that the next visit already has a reason to exist.",
        "Our active first-visit outline uses nine nights: one near the arrival airport, two around Sigiriya, one in Kandy, two in the hills and three on the south coast. It is still a moving journey, not a slow holiday. If you prefer fewer transfers, remove either Kandy and the hills or the Cultural Triangle, then give those nights to the remaining places. Do not simply compress the same route."),
      s("Day one: arrive without proving anything",
        "After a long flight, a first night near the airport can be more sensible than immediately starting a major road transfer. Negombo is a practical possibility; choose the actual hotel according to arrival time and onward route. If your flight lands early and you are comfortable with a longer first day, discuss going directly inland with your driver—but understand what that does to the day.",
        "Confirm who is meeting you, the vehicle arrangements and how meals and stops will work. A good driver or guide is part of the trip, not merely a means of connecting hotels. Give them the priorities in advance and invite a realistic response to the schedule. An itinerary becomes more useful when someone is allowed to say that it is too full."),
      s("Days two and three: give the Cultural Triangle two nights",
        "Base around Sigiriya rather than changing rooms between nearby cultural visits. Sigiriya and Dambulla reward attention, but they are not interchangeable photo stops: allow for climbing, heat, appropriate clothing and time to understand what you are seeing. Check current opening and ticket arrangements with the relevant sites before travelling.",
        "Do not add every major ruin because it appears in the same regional description. Choose the visit that most interests you and leave a quieter interval around it. A pool or garden at the hotel has particular value here, not as a status symbol but as a place to recover from a demanding morning. The best itinerary is not the one with the most impressive list of names."),
      s("Days four to six: Kandy and the hills, selectively",
        "One night in Kandy creates a break in the journey and an opportunity for a focused cultural visit. Two nights in one hill-country base then give the landscape a chance to become more than a view through a window. Choose the base for the activities you actually want—walking, tea-country scenery or a quieter hotel stay—rather than assuming every hill town offers the same thing.",
        "If a train journey is central to the plan, check current services and reservation availability before fixing the rest of the route around it. Do not treat an unconfirmed seat as a booking. Equally, do not feel obliged to spend an entire day on a famous journey if a shorter section suits your schedule better. The experience should serve the holiday, not consume it."),
      s("Days seven to ten: let the coast be the finish",
        "Three nights on the south coast provide a proper change of rhythm before departure. Ahangama suits travellers who want coastal life around them; Abode by the Beach offers two oceanfront suites, distinct from the brand's garden property. A larger hotel around Weligama answers a different need for facilities and scale. Choose the setting and swimming arrangements deliberately, and seek current local advice about sea conditions.",
        "Season matters: Sri Lanka's coasts do not share one simple year-round weather pattern. Check conditions for your dates before committing to this south-coast finish; an east-coast alternative may require redesigning the route, not merely changing the final hotel. On day ten, allow a conservative airport transfer or add a final airport-area night if the flight demands it. If wildlife is essential, replace a chapter with a safari stay. Do not bolt it onto an itinerary that is already doing enough."),
    ],
  },
  "marrakech-sensory-guide": {
    updated, title: "Marrakech: A Better Plan Than Getting Lost",
    dek: "Choose your base, organise the first arrival and leave enough space for the city to become intelligible.",
    excerpt: "Marrakech planning advice: medina riad versus resort, arrival logistics, official garden tickets, souk visits and a balanced three-day stay.",
    hotelSlugs: ["la-mamounia", "royal-mansour-marrakech"], heroImage: "/hotels/royal-mansour-marrakech-official.jpg", cardImage: "/hotels/royal-mansour-marrakech-official.jpg", imageAlt: "Architecture and gardens at Royal Mansour Marrakech",
    sources: [{ label: "Marrakech destination information", url: "https://www.visitmorocco.com/en/travel/marrakesh" }, { label: "Official Jardin Majorelle tickets", url: "https://www.jardinmajorelle.com/lejardinmajorelle/" }],
    sections: [
      s("Choose what happens when you step outside",
        "Marrakech is often sold as an exercise in surrender: lose yourself in the lanes, follow a scent, let the city overwhelm you. There is pleasure in wandering, but a good holiday does not require being permanently disoriented. A little structure makes the experience more generous. Know how to reach your hotel, give the first outing a manageable shape and save the romantic aimlessness for when you have found your bearings.",
        "Your address does much of the planning. A medina riad places the old city's streets close at hand, often with a final approach on foot. A hotel with larger grounds offers a different balance of activity and retreat. More distant resort settings make spontaneous city outings less effortless. Choose the version that suits your days rather than treating every courtyard photograph as the same product."),
      s("Make the first arrival uncomplicated",
        "Ask the hotel for its current drop-off point and whether someone will meet you for the last part of the journey. Save those instructions before travelling. A driver reaching the nearest accessible road is not necessarily the same as reaching reception, and a map pin may not explain the difference. Luggage is easier when the final approach has been discussed rather than improvised.",
        "On the first evening, keep dinner near the hotel or in-house. This is not an argument against exploration; it is a way to begin without turning fatigue into a judgment about the city. The following morning will feel different when you have slept, know the route home and have a clearer sense of the area around you."),
      s("Give the medina a subject",
        "Instead of attempting to see everything, choose a focus for a guided walk: architecture, particular crafts or the organisation of the markets. Agree on duration, cost and expectations in advance, including whether shopping stops are part of the route. A good visit should leave you understanding more, not simply carrying more bags.",
        "When buying something substantial, take time over material, workmanship, dimensions and delivery arrangements. Admiration does not oblige a purchase, and a hurried bargain can become an expensive object you never wanted. Ask before photographing people or working spaces. The city is not a set assembled for visitors; a more attentive approach tends to produce a more interesting encounter."),
      s("Book the garden through the right door",
        "Jardin Majorelle's official website identifies its authorised online ticket route. Use that rather than assuming the first result in a search is the garden itself. Check which spaces your ticket covers, the entry time and any related museum bookings before arranging the rest of the day. A famous garden is more enjoyable when you are not trying to solve admission at the pavement.",
        "Keep the surrounding schedule light enough to let the visit be a visit rather than a countdown. One substantial cultural stop and time for lunch can be a better day than three timed entries tied together by anxious transfers. The same principle applies to palaces and museums: verify current opening arrangements, then leave room for the things that do not require a reservation."),
      s("The hotel should change the pace", 
        "A garden, courtyard or quiet room matters in Marrakech because contrast is part of the pleasure. La Mamounia and Royal Mansour offer expansive, highly composed versions of retreat; a smaller riad may offer a more intimate one. Look beyond the most photogenic public space to the room itself: daylight, stairs, privacy and proximity to shared dining areas deserve attention.",
        "For three days, we would build around one orientation walk, one planned cultural visit and one less scheduled day, with generous intervals for meals and rest. Do not make a distant excursion compulsory merely because it is commonly sold as an add-on. Marrakech is already a substantial subject. The city becomes more memorable when you give it enough time to move beyond the initial impression of colour and noise."),
    ],
  },
  "amalfi-coast-where-to-stay": {
    updated, title: "Where to Stay on the Amalfi Coast: Choose Your Vertical", 
    dek: "The view is only half the address. The other half is how you get back to your room.",
    excerpt: "Compare Positano, Amalfi, Ravello, Minori and Maiori for an Amalfi Coast stay, with honest advice on stairs, ferries, transfers and hotel location.",
    heroImage: "/hotels/belmond-hotel-caruso-official.jpg", cardImage: "/hotels/belmond-hotel-caruso-official.jpg", imageAlt: "Belmond Hotel Caruso overlooking the Amalfi Coast from Ravello",
    sources: [{ label: "Travelmar ferry questions", url: "https://www.travelmar.it/en/faq" }, { label: "Travelmar connections for the Path of the Gods", url: "https://www.travelmar.it/en/how-to-reach-path-of-gods" }],
    sections: [
      s("The postcard leaves out the return journey",
        "The Amalfi Coast's most flattering angle is usually from somewhere above it. That is also the source of its most common booking mistake: choosing a spectacular view without understanding the climb between the hotel, dinner and the water. Before comparing pools, establish the practical route from the arrival point to reception. Ask about steps, vehicle access and luggage assistance in plain numbers and clear terms.",
        "There is no single best town for everyone. Positano offers the famous vertical composition; Amalfi is useful for exploring by sea when services operate; Ravello trades immediate waterfront access for elevation and gardens. Minori and Maiori deserve consideration if you prefer a different balance of town life and waterfront. The right base is the one whose daily logistics do not undermine its beauty."),
      s("Positano: buy the view with your eyes open",
        "Positano is particularly seductive from a balcony. Its layered buildings and steep setting make the view feel architectural as much as coastal. But a room described as close to the beach may be close on a map rather than easy to reach. Establish the walking route, not just the distance, and consider how often you expect to make it.",
        "For anyone with mobility concerns, this is essential rather than fussy. Ask the hotel to describe the complete arrival and beach journey, including internal steps and any lift limitations. If you want to spend much of the stay at the property, a higher location may be precisely right. If you want repeated easy outings, the same address can become a daily negotiation."),
      s("Amalfi: a practical base, not just a famous name",
        "Amalfi can work well when the holiday involves exploring several coastal towns. Check the seasonal ferry timetable for your dates rather than treating sea connections as permanent infrastructure. Weather can interrupt services, so keep a road alternative and avoid building a departure around the last possible boat. Travelmar's tickets are for specific journeys, not an unlimited hop-on, hop-off pass.",
        "A central address helps if you want to leave the hotel frequently. A property beyond the busiest streets can offer more separation, but the return journey deserves the same scrutiny as in Positano. Do not assume a shuttle operates whenever you want it; ask about hours, frequency and reservation requirements before allowing it to solve your entire transport plan."),
      s("Ravello: stay for the height",
        "Ravello's appeal is different. You come for the elevated setting and a sense of distance from the waterfront's immediate activity. A hotel such as Caruso makes the grounds and outlook central to the experience. It is a good choice if an afternoon at the hotel sounds like part of the holiday rather than a failure to explore.",
        "It is not a beachfront base. If daily sea swimming is the non-negotiable priority, calculate the journey before falling for the pool photograph. A Ravello stay and a waterfront stay can make a meaningful longer-trip split, but changing hotels on a short visit may cost more in time than it adds in variety. One well-matched base is often enough."),
      s("Minori, Maiori and the plan you can sustain",
        "Consider Minori and Maiori if your ideal coast holiday is less dependent on the most recognisable skyline. Examine each hotel's actual position: even a town with a more accessible waterfront can have hillside accommodation. Spend the saved attention on meals, walks and a few well-chosen journeys rather than assuming you must visit every celebrated address.",
        "For the Path of the Gods or another substantial walk, plan the start and finish separately from the enthusiasm generated by the photographs. Check current access, weather and transport; Travelmar publishes information on its ferry-and-bus connection to Bomerano. Keep departure day conservative, particularly when connecting to a train or flight. The coast rewards a little logistical humility. The view will still be there if you allow the journey enough time."),
    ],
  },
  "paris-for-grown-ups": {
    updated, title: "Paris for Grown-Ups: Fewer Reservations, Better Days",
    dek: "Choose a neighbourhood, give one museum your attention and stop treating dinner as a competitive sport.",
    excerpt: "A considered Paris city break: choosing a hotel neighbourhood, planning museums, making useful restaurant reservations and leaving room to explore.",
    heroImage: "/hotels/the-ritz-paris.jpg", cardImage: "/hotels/the-ritz-paris.jpg", imageAlt: "Ritz Paris on Place Vendôme",
    sources: [{ label: "Paris by district", url: "https://parisjetaime.com/eng/paris-by-district-i153" }, { label: "Musée d'Orsay visitor information", url: "https://www.musee-orsay.fr/en/visit" }],
    sections: [
      s("A city break is not an examination",
        "There comes a point when the most desirable Paris itinerary is no longer the one containing the most Paris. You have seen enough photographs to know that the monuments exist. What you want is a few days with a satisfying shape: a good room, somewhere nearby for coffee, one visit that deserves concentration and dinner that does not require crossing the city in a state of mild panic.",
        "That is not an argument for incuriosity. It is an argument for depth. Choose a neighbourhood you would enjoy returning to at different hours and let it provide the ordinary parts of the stay. A city becomes more legible through repetition: the same street before shops open, after lunch and on the way home. Constantly changing districts can make even a long weekend feel like a series of introductions."),
      s("Book the address you will use",
        "The area around Place Vendôme makes sense if the formal elegance of central Paris is part of the attraction; the Ritz belongs to that particular dream. A Left Bank address offers another set of daily habits, while the Marais suggests a different pattern of walking and browsing. Choose according to the places you genuinely want to spend time, not a vague claim that one arrondissement is universally best.",
        "Room size, lift access and sound insulation deserve the same attention as the lobby. A compact room can be perfectly adequate when the neighbourhood is your sitting room, but less so if you need to work or rest indoors. Ask about the specific category. Parisian charm does not oblige you to be uncomfortable, and a prestigious address does not automatically provide a quiet bedroom."),
      s("Give one museum a proper part of the day",
        "Pick the collection that interests you most and allow it enough time. The Musée d'Orsay, for example, publishes its current opening and booking information; it is ordinarily closed on Mondays and has a later Thursday opening. Verify arrangements for your dates, including special closures, rather than building a day from an old recommendation.",
        "A timed ticket settles admission, not how much attention you have. Resist attaching another major museum immediately afterwards simply because the journey looks short. Choose a few rooms or artists to spend time with, then leave before fatigue turns the rest into furniture. A walk and lunch afterwards can deepen the experience more effectively than another queue."),
      s("Reserve the meal you care about, not every meal",
        "If a particular restaurant is central to the trip, book it through its current official channel and read the cancellation terms. Then leave other meals more flexible. The problem with a fully reserved city break is that appetite and curiosity become subordinate to the calendar. You can end up leaving a neighbourhood you are enjoying to honour a lunch chosen weeks earlier for no especially good reason.",
        "Choose the dinner location in relation to the day. A local table after a long outing is often more satisfying than a famous one requiring another substantial journey. When considering an expensive menu, compare the total likely spend, including drinks, rather than the headline price alone. The right meal is the one you can enjoy without mentally renegotiating the rest of the holiday."),
      s("Leave a morning unassigned",
        "An unplanned morning needs a starting point, not an agenda. Walk from the hotel, find breakfast and follow one thread that interests you: bookshops, architecture, a market or the river. Use public transport when it helps, but do not let an efficient route become the reason for a visit. Paris rewards intervals in which you are not required to prove that the time has been well spent.",
        "For three nights, our preferred structure is modest: one substantial cultural reservation, one dinner worth arranging in advance and several loose neighbourhood walks. Add more only if that is genuinely how you like to travel. The mature luxury is not access to every door. It is the confidence to leave some closed, return to a place you liked yesterday and allow the city to become familiar rather than merely completed."),
    ],
  },
};
