import type { Hotel } from "../hotels";

export const septemberHotels: Hotel[] = [
  {
    slug: "the-imperial-new-delhi",
    name: "The Imperial New Delhi",
    city: "New Delhi",
    country: "India",
    region: "Asia",
    category: "Capital Grand Dame",
    tagline: "Delhi history told through Deco geometry, high ceilings and eight gardened acres",
    excerpt: "The Imperial is New Delhi's great historical hotel: a 1936 landmark on Janpath with a formidable art collection, mature gardens and the rare confidence to let the building speak first.",
    rating: 4.7,
    priceFrom: 310,
    priceNote: "Indicative; seasonal and before taxes",
    year: "September 2026",
    heroImage: "https://tablecells.com/api/v1/files/public/01KY9WNE0247F8D82ED5JQCY7A-the-imperial-india-hero-image.png",
    cardImage: "https://tablecells.com/api/v1/files/public/01KY9WNE0247F8D82ED5JQCY7A-the-imperial-india-hero-image.png",
    hotelsUrl: "https://www.hotels.com/ho188603/the-imperial-new-delhi-new-delhi-india/",
    imageAlt: "The white heritage façade and entrance of The Imperial New Delhi on Janpath",
    standout: "Walking the long marble corridors at dusk, past colonial-era paintings and Deco details, before the gardens swallow the noise of Janpath.",
    quickFacts: [
      { label: "Location", value: "Janpath, central New Delhi" },
      { label: "Rooms", value: "192 rooms & 43 suites" },
      { label: "Opened", value: "1936" },
      { label: "Best for", value: "History, art, first-time Delhi" },
    ],
    sections: [
      { body: [
        "New Delhi was barely two decades old when The Imperial opened in 1936, and the hotel still carries the self-belief of a capital being invented. Its pale façade, deep portico and long corridors borrow from Victorian ceremony, Art Deco precision and the imperial plan of Lutyens' Delhi without collapsing into pastiche. This is not a palace transplanted from Rajasthan. It is a city hotel built for administrators, diplomats, travellers and the charged conversations of a country approaching independence.",
        "The location on Janpath is unusually useful. Connaught Place, the museums around India Gate and the ceremonial avenues of central Delhi sit within easy reach, yet eight acres of gardens establish a genuine remove from the traffic. The transformation happens at the driveway: horns recede, palms take over and the building resumes its slow, composed rhythm.",
      ]},
      { heading: "History without the museum ropes", body: [
        "The Imperial's greatest asset is not a swimming pool or suite category but its accumulated atmosphere. Works from a substantial collection of colonial and post-colonial art line the public rooms. Photographs, lithographs and military portraits make the corridors a visual record of how power once presented itself, while the hotel's own story intersects with the final years of British rule and the birth of modern India.",
        "That history can be uncomfortable, and the hotel is most interesting when treated as evidence rather than nostalgia. The architecture is beautiful; the era it represents was not innocent. To walk here attentively is to encounter both things at once, which gives The Imperial a depth that a newly built 'heritage' hotel cannot manufacture.",
      ]},
      { heading: "The rooms: choose character over acreage", body: [
        "The 192 rooms and 43 suites range from compact Deco rooms to grand apartments. Entry rooms can feel modest beside Delhi's newer palaces, though high ceilings, solid doors and marble bathrooms preserve the sense of occasion. Heritage and Grand Heritage categories are the sweet spot: enough space to exhale, stronger architectural detail and views towards the gardens rather than the atrium.",
        "Suites carry more antiques, patterned stone and the deliberate formality of the house. Ask about distance from the lifts and the outlook; this is a long, historic building and two rooms bearing the same label can inhabit very different corners. Travellers seeking touchscreens and fashion-hotel theatre will find the technology discreet and the palette restrained. That is the point, although sockets and lighting can feel less intuitive than at a new build.",
      ]},
      { heading: "A dining room worth dressing for", body: [
        "The Spice Route remains the visual event, an extraordinary sequence of spaces inspired by the historic trading path from the Malabar Coast across Southeast Asia. Hand-painted surfaces, carved timber and temple-like details could overwhelm the meal, yet the kitchen's southern Indian and Southeast Asian flavours have enough acidity and heat to hold their own. Book ahead and allow time to look before sitting down.",
        "1911 provides the all-day heartbeat; the bar next door is better after dark, when diplomats, regulars and hotel guests share the room without anyone announcing a concept. Breakfast can be busy, but service retains an old-school willingness to solve a problem rather than explain a policy.",
      ]},
      { heading: "The gardens change the stay", body: [
        "Delhi's air, heat and traffic make outdoor space more than decoration. The Imperial's lawns and mature trees let a day in the city end gradually. The long pool feels secluded, the spa offers an effective retreat and breakfast outside in forgiving weather is one of the hotel's simplest luxuries.",
        "Families gain breathing room and business travellers can hold a conversation without being trapped in a lobby. During wedding season, however, tranquillity depends on the event calendar. Ask before booking if silence matters.",
      ]},
      { heading: "The verdict", body: [
        "The Imperial is not Delhi's largest room, newest spa or most theatrical palace. It is something harder to replace: a hotel inseparable from the making of the city around it. Stay for the architecture, the art and the sensation of inhabiting history rather than observing it from a tour bus. Accept a few old-building eccentricities, choose the room carefully and give the hotel time. It rewards attention.",
      ]},
    ],
    featured: true,
  },
  {
    slug: "the-lodhi-new-delhi",
    directBookingUrl: "https://www.thelodhi.com/",
    name: "The Lodhi",
    city: "New Delhi",
    country: "India",
    region: "Asia",
    category: "Modern City Resort",
    tagline: "Kerry Hill calm, monumental space and private pools on Delhi's greenest edge",
    excerpt: "The Lodhi turns a central Delhi address into an unusually private urban resort, with vast rooms, plunge-pool suites, serious fitness facilities and Indian Accent downstairs.",
    rating: 4.8,
    priceFrom: 290,
    priceNote: "Indicative; seasonal and before taxes",
    year: "September 2026",
    heroImage: "https://thelodhi.com/wp-content/uploads/sites/4/2025/03/Lodhi-Room-2.jpg",
    cardImage: "https://thelodhi.com/wp-content/uploads/sites/4/2025/03/Lodhi-Room-2.jpg",
    hotelsUrl: "https://www.hotels.com/ho310789/the-lodhi-a-member-of-the-leading-hotels-of-the-world-new-delhi-india/",
    imageAlt: "A spacious room at The Lodhi New Delhi with timber screens and garden light",
    standout: "Closing the door on a 129-square-metre Lodhi Room and stepping into a private plunge pool while Humayun's Tomb rises beyond the trees.",
    quickFacts: [
      { label: "Location", value: "Lodhi Road, New Delhi" },
      { label: "Design", value: "Kerry Hill Architects" },
      { label: "Signature", value: "Rooms with private plunge pools" },
      { label: "Best for", value: "Space, wellness, food" },
    ],
    sections: [
      { body: [
        "Delhi rarely deals in understatement, which makes The Lodhi's composure feel almost radical. The building uses sandstone, deep shadow, water and monumental screens to create privacy beside one of the capital's most useful roads. Kerry Hill's architecture is modern but not placeless: jaali patterns regulate the light, courtyards slow the route through the hotel and views catch gardens, domes and treetops rather than a generic skyline.",
        "Its geography is excellent for a certain Delhi. Humayun's Tomb, Nizamuddin, Lodhi Gardens and Khan Market are close; Old Delhi is not. The property behaves like a resort without abandoning the city, a difficult balance that explains why both weekenders and people with serious work to do become repeat guests.",
      ]},
      { heading: "Rooms designed around privacy", body: [
        "The entry Executive Rooms are already generous at just over 51 square metres and include proper balconies. The reason to trade up is the Lodhi Room: roughly 129 square metres with a private plunge pool, large dressing area and enough separation between bed and bath to make the room feel residential. Higher floors exchange some garden intimacy for wider views towards Humayun's Tomb.",
        "The design is quieter than the dimensions suggest. Stone, timber and neutral fabrics leave space for the architecture; glass walls and long sightlines make the rooms feel even larger. Plunge pools are not all equally private, and Delhi's winter can change how much they are used, so ask about floor, outlook and heating before spending the premium.",
      ]},
      { heading: "A hotel with an athletic club, not a token gym", body: [
        "The 50-metre temperature-controlled pool is the headline, but the depth of the fitness offer is what distinguishes The Lodhi: tennis, squash, Pilates, yoga and a gym that expects people to train rather than pose beside a treadmill. The spa has scale and calm, with treatments drawing on Indian ingredients without turning wellness into a costume.",
        "This infrastructure gives long stays a convincing rhythm. It also brings club members into the hotel, which is good for atmosphere but means some spaces feel social rather than secluded at peak times.",
      ]},
      { heading: "Indian Accent changes the equation", body: [
        "Indian Accent is not merely the best-known restaurant in the building; it is one of the reasons to choose the hotel. The cooking uses memory as raw material—familiar street snacks, regional curries and nostalgic combinations sharpened through technique—without losing the emotional directness that made the dishes matter. A reservation should be made when the room is booked, not after arrival.",
        "Perbacco brings contemporary Italian cooking and a deep cellar; Élan handles the all-day brief with more personality than most hotel restaurants. The Safari Lounge is theatrical and late-running. Taken together, the food and drink make staying in unusually tempting, though Delhi's independent restaurant scene deserves resistance.",
      ]},
      { heading: "Where the polish catches", body: [
        "Scale can occasionally work against intimacy. Corridors are long, the architecture is imposing and service can feel formal before it warms. The plunge-pool categories also create expectations that weather and privacy do not always satisfy. Guests who want a small hotel where the owner appears at breakfast should look elsewhere.",
        "What The Lodhi does better than almost any city hotel in India is give a traveller space without exile. The airport, ministries and monuments are all reachable, but the day ends in water, gardens and a room large enough to recover properly.",
      ]},
      { heading: "The verdict", body: [
        "Book The Lodhi when Delhi needs to be both destination and working city. It is less storied than The Imperial, less ceremonially palatial than The Leela and more physically indulgent than either. For design-minded travellers who value privacy, serious exercise and dinner at Indian Accent, it may be the capital's most complete contemporary stay.",
      ]},
    ],
    featured: true,
  },
  {
    slug: "the-leela-palace-new-delhi",
    directBookingUrl: "https://www.theleela.com/the-leela-palace-new-delhi",
    name: "The Leela Palace New Delhi",
    city: "New Delhi",
    country: "India",
    region: "Asia",
    category: "Diplomatic Palace",
    tagline: "A modern palace that understands Delhi's appetite for ceremony",
    excerpt: "The Leela Palace delivers the capital at full volume: generous rooms, a rooftop pool, ambitious restaurants and polished service in the Diplomatic Enclave.",
    rating: 4.6,
    priceFrom: 280,
    priceNote: "Indicative; seasonal and before taxes",
    year: "September 2026",
    heroImage: "https://www.theleela.com/prod/content/assets/aio-banner/dekstop/ND-desk_0.jpg?VersionId=058xQUm3hYwiePe4pqi.ei.a3AJlDpc0",
    cardImage: "https://www.theleela.com/prod/content/assets/2026-01/Hero-image-leela-new-delhi.webp?VersionId=eaYoYPgYfN3pXpnWsT4AIhQ8UnOw7OkY",
    hotelsUrl: "https://www.hotels.com/ho353117/the-leela-palace-new-delhi-new-delhi-india/",
    imageAlt: "The Leela Palace New Delhi illuminated in the Diplomatic Enclave",
    standout: "Swimming across the rooftop pool at sunset as the broad, low skyline of diplomatic Delhi turns amber beneath you.",
    quickFacts: [
      { label: "Location", value: "Chanakyapuri, Diplomatic Enclave" },
      { label: "Rooms", value: "254 rooms & suites" },
      { label: "Opened", value: "2011" },
      { label: "Best for", value: "Celebrations, dining, rooftop pool" },
    ],
    sections: [
      { body: [
        "The Leela Palace does not whisper. It rises in Chanakyapuri like a modern interpretation of the palaces Delhi might have built had the princely states commissioned hotels instead of residences: sandstone, domes, chandeliers, hand-worked details and staff who understand arrival as theatre. The proportions are generous and the mood unapologetically formal.",
        "That confidence suits the Diplomatic Enclave. Embassies, broad avenues and established residential districts surround the hotel; the airport is more convenient than from Old Delhi, while India Gate and the central museums remain close enough for an early start. The immediate neighbourhood is orderly rather than walkable, so a car is essential.",
      ]},
      { heading: "Rooms made for long-haul recovery", body: [
        "Entry rooms begin at a substantial 51 square metres, with deep mattresses, proper desks and marble bathrooms that do not make couples negotiate for space. Premiere rooms are larger still, while Royal Club categories add lounge access and butler service. The palette—gold, red, polished timber and patterned textiles—continues the palace argument upstairs.",
        "The strongest rooms face the inner garden or wider city rather than service areas. Technology has improved, but the visual language remains traditional and can feel emphatic beside The Lodhi's restraint. Travellers should decide whether they want Delhi interpreted through splendour or calm; The Leela is firmly on the side of splendour.",
      ]},
      { heading: "Restaurants with independent gravity", body: [
        "Megu's dramatic ropes, lacquer and precise Japanese cooking make it more than a hotel dining room. Le Cirque handles Franco-Italian occasion dining, while Jamavar brings polished Indian regional dishes into a setting designed for celebration. The Qube is the practical all-day option and the Library Bar offers the best transition from meeting to evening.",
        "The range matters because Delhi traffic punishes casual indecision. A guest can eat very well for several nights without leaving, though prices reflect the captive convenience. Reservations are sensible during diplomatic events and wedding season.",
      ]},
      { heading: "The rooftop earns its place", body: [
        "Many city pools are an architectural afterthought. The Leela's rooftop pool is a destination: open sky, framed pavilions and a view across a surprisingly green part of the capital. Winter sun is particularly seductive; summer afternoons require strategy. The spa below supplies a quieter counterpoint and has the treatment depth expected of a palace hotel.",
        "Ceremonial rituals and attentive butler service add character, though the choreography can occasionally feel over-composed. The hotel is at its best when the formality relaxes into genuine warmth.",
      ]},
      { heading: "Who should book it", body: [
        "The Leela is exceptionally good for milestone trips, multigenerational families and travellers who want every practical need handled inside the building. Rooms are forgiving, restaurants varied and the airport route manageable. Minimalists and guests hoping to step directly into a neighbourhood of cafés may feel contained.",
        "Ask about functions before arrival. The hotel's scale allows events and individual stays to coexist, but weddings can change the tempo of public rooms. Club access is worthwhile when the diary is meeting-heavy or privacy matters.",
      ]},
      { heading: "The verdict", body: [
        "This is Delhi luxury without an apology: polished, expansive and theatrical, with enough operational competence beneath the marble to keep the performance from becoming exhausting. The rooftop pool and room size are the decisive advantages. Come prepared to embrace ceremony and The Leela Palace becomes a persuasive capital address.",
      ]},
    ],
  },
  {
    slug: "taj-mahal-palace-mumbai",
    directBookingUrl: "https://www.tajhotels.com/en-in/hotels/taj-mahal-palace-mumbai",
    name: "The Taj Mahal Palace",
    city: "Mumbai",
    country: "India",
    region: "Asia",
    category: "Harbour Icon",
    tagline: "The hotel that became part of Mumbai's idea of itself",
    excerpt: "Facing the Gateway of India since 1903, the Taj is more than Mumbai's most recognisable hotel: it is a living civic landmark with Palace rooms, historic restaurants and an incomparable address.",
    rating: 4.8,
    priceFrom: 310,
    priceNote: "Indicative; seasonal and before taxes",
    year: "September 2026",
    heroImage: "https://live.staticflickr.com/1510/26119514800_9bb7893876_o.jpg",
    cardImage: "https://live.staticflickr.com/1510/26119514800_9bb7893876_o.jpg",
    hotelsUrl: "https://www.hotels.com/ho623671776/the-taj-mahal-palace-mumbai-mumbai-india/",
    imageAlt: "The Taj Mahal Palace façade beside the Gateway of India in Mumbai",
    standout: "Opening the curtains on a Palace Wing sea-view room to find the Gateway of India, ferries and the whole harbour morning arranged below.",
    quickFacts: [
      { label: "Location", value: "Apollo Bunder, Colaba" },
      { label: "Rooms", value: "243 rooms & 42 suites" },
      { label: "Opened", value: "1903" },
      { label: "Best for", value: "History, first-time Mumbai, views" },
    ],
    sections: [
      { body: [
        "The Taj Mahal Palace opened in 1903, two decades before the Gateway of India beside it, and that inversion explains its place in Mumbai. The hotel does not merely enjoy the city's iconic view; it helped create it. Its red dome and Indo-Saracenic façade have welcomed ships, statesmen, film stars, families and generations of residents who use the lobby as civic space.",
        "A stay begins in a crowd because this is a landmark as well as a hotel. Security is serious, afternoon tea is busy and cameras appear in the public rooms. Yet pass into the Palace Wing corridors or the pool courtyard and the scale becomes more intimate. The Taj's accomplishment is preserving emotional warmth inside an institution.",
      ]},
      { heading: "Palace Wing or Tower Wing?", body: [
        "The choice defines the stay. Palace Wing rooms carry higher ceilings, arches, period details and the romance people imagine when booking the Taj. They also vary more in plan and outlook. The Tower Wing is cleaner-lined and often more straightforward, with broad harbour or city views and easier access to some facilities.",
        "For a first visit, a Palace Wing sea-view room is worth the premium. The Gateway, boats and Arabian Sea animate the window from dawn. Ask precisely what the category faces: 'sea view' and 'city view' contain meaningful differences in a building with several orientations. Taj Club access can improve a short, busy stay through breakfast, transfers and evening drinks.",
      ]},
      { heading: "A hotel as a dining district", body: [
        "The restaurant list reads like a piece of Mumbai hospitality history. Harbour Bar lays claim to being the city's first licensed bar; Sea Lounge remains the classic place for tea with the water outside. Golden Dragon has fed generations of regulars, while Wasabi by Morimoto gives the hotel serious contemporary Japanese credentials. Loya brings the cooking of northern India into a more theatrical frame.",
        "Not every outlet will feel equally urgent, and prices can outpace the cooking. The pleasure is range and continuity: breakfast, a formal dinner, a late drink and a nostalgic tea can unfold under one roof without feeling like versions of the same room.",
      ]},
      { heading: "Service after history", body: [
        "The hotel's modern meaning cannot be separated from the 2008 attacks or from the staff whose courage became part of its story. That history deserves respect, not tourist spectacle. What survives in daily service is a powerful institutional instinct: porters who read a confused arrival, concierges who understand the city's distances and waiters who remember families across years.",
        "Scale inevitably produces seams. Check-in can back up, popular public spaces attract non-residents and a request may pass through several hands. At its best, the Taj responds not with scripted apology but with ownership.",
      ]},
      { heading: "Colaba at the door", body: [
        "Few Indian luxury hotels offer a better immediate neighbourhood. The Gateway is outside; Colaba Causeway, galleries, cafés and the lanes of Fort are walkable. Boats leave for Elephanta Island nearby. Early morning is the secret hour, before heat and visitors thicken the waterfront.",
        "The airport is distant and Mumbai traffic has no respect for published driving times. This is a South Mumbai base, ideal for Colaba, Fort and Marine Drive but inefficient for meetings in Bandra or the northern business districts.",
      ]},
      { heading: "The verdict", body: [
        "Some landmark hotels trade entirely on their silhouette. The Taj still justifies the room key through service, restaurants and a location that changes how Mumbai is experienced. Book the Palace Wing, insist on the right view and leave time to walk. You are not staying beside the history of the city; for a night or two, you are staying inside it.",
      ]},
    ],
    featured: true,
  },
  {
    slug: "the-oberoi-mumbai",
    directBookingUrl: "https://www.oberoihotels.com/hotels-in-mumbai/",
    name: "The Oberoi, Mumbai",
    city: "Mumbai",
    country: "India",
    region: "Asia",
    category: "Waterfront Modernist",
    tagline: "Wall-to-wall Arabian Sea and an operation tuned to quiet competence",
    excerpt: "The Oberoi turns Nariman Point into a precise urban refuge: exceptional service, refreshed rooms, immense windows and front-row views of Marine Drive's Queen's Necklace.",
    rating: 4.7,
    priceFrom: 260,
    priceNote: "Indicative; seasonal and before taxes",
    year: "September 2026",
    heroImage: "https://www.oberoihotels.com/-/media/oberoi-hotel/the-oberoi-mumbai/mumbai-1-8-24/overview/banner/desktop1920x980/banner3_.jpg",
    cardImage: "https://www.oberoihotels.com/-/media/oberoi-hotel/the-oberoi-mumbai/mumbai-1-8-24/overview/banner/desktop1920x980/banner3_.jpg",
    hotelsUrl: "https://www.hotels.com/ho123895/the-oberoi-mumbai-mumbai-india/",
    imageAlt: "The Oberoi Mumbai at Nariman Point overlooking the Arabian Sea",
    standout: "Watching Marine Drive ignite curve by curve from a wall of glass while room service arrives exactly when promised.",
    quickFacts: [
      { label: "Location", value: "Nariman Point, South Mumbai" },
      { label: "Views", value: "Arabian Sea & Queen's Necklace" },
      { label: "Signature", value: "24-hour personalised service" },
      { label: "Best for", value: "Business, service, sea views" },
    ],
    sections: [
      { body: [
        "The Oberoi is not the oldest or most photogenic hotel in Mumbai. It may be the one most likely to make a difficult day work. Rising at Nariman Point where the business district meets the Arabian Sea, it combines wall-to-wall views with an operating culture built around anticipation. Luggage disappears, laundry returns, cars materialise and breakfast adjusts to a departure without the machinery becoming visible.",
        "The lobby is contemporary and controlled, less civic theatre than the Taj and less social stage than a fashionable Bandra hotel. This can read as corporate on first encounter. Stay long enough to notice the quality of the decisions—lighting that works, staff who retain context, a room arranged for both sleep and serious work—and restraint begins to feel luxurious.",
      ]},
      { heading: "The view is the room", body: [
        "Refreshed Premier rooms use a calm palette, excellent beds and standalone baths, but the defining choice is orientation. Ocean View looks west over open water; Queen's Necklace views catch the luminous arc of Marine Drive and are particularly dramatic after dark. City categories are comfortable but miss the hotel's essential argument.",
        "Suites add separate living space, but even standard rooms feel generous because glazing replaces a wall. Bathrooms often share the outlook through switchable glass. Ask for the highest available floor and confirm whether the promised view is sea, bay or city; the terms are not interchangeable.",
      ]},
      { heading: "Service as infrastructure", body: [
        "Oberoi service is warm without becoming familiar too quickly. A single request tends to remain solved, and the hotel is especially good at the invisible logistics of business travel: pressing, airport timing, documents, dietary needs and late meals. Solo travellers receive thoughtful attention without being fussed over.",
        "No large hotel is seamless. The ground-floor arrival can feel subdued and breakfast rushes expose the scale. Yet recovery is usually swift because staff are empowered to fix rather than escalate.",
      ]},
      { heading: "Eating above the water", body: [
        "Ziya brings contemporary Indian cooking by Vineet Bhatia into a room framed by sea; Vetro handles Italian food with clarity, while Fenix ranges widely enough for mixed groups and long stays. Eau Bar is the useful room: elegant, comfortable and capable of moving from an early meeting to a late drink without changing costume.",
        "The Trident next door expands the dining universe, and South Mumbai's restaurants are close enough to resist staying in. Still, an ocean-facing breakfast after an early walk on Marine Drive is difficult to improve.",
      ]},
      { heading: "Nariman Point: privilege and compromise", body: [
        "Marine Drive begins outside, the National Centre for the Performing Arts is close and Colaba and Fort are a short drive. Dawn walkers, runners and chai sellers give the waterfront a democratic energy the polished hotel cannot create for itself.",
        "The compromise is Mumbai's northward geography. The airport, Bandra and BKC can consume hours. Choose The Oberoi when the trip belongs primarily to South Mumbai or when the hotel itself needs to compensate for a punishing diary.",
      ]},
      { heading: "The verdict", body: [
        "The Oberoi, Mumbai is a masterclass in friction removed. It does not offer the Taj's heritage or a private club's scene, but it delivers sleep, space, service and one of the city's finest views with formidable consistency. For business travellers and anyone who believes competence is the highest form of luxury, this is the address.",
      ]},
    ],
  },
];
